# Learn Numpy Full course 58 mins


1. for 1D array there will be only one axis which is axis=0 which means along the rrow.
2. for 2D array,there will be two axes which are axis=0 and axis=1

In [1]:
# notes wriiten for first 10 mins .pls check it once.

In [4]:
import numpy as np
a=np.array([1,2,3,4,5])

In [6]:
a.dtype # gives the datatype of the array

dtype('int32')

In [7]:
a[0].dtype

dtype('int32')

In [9]:
a=np.array([1,2,3,4,5],dtype='int16') 
# we can also give the datatype whatever we want. # int16 means integer value with 2 bytes of memory.

In [10]:
a.dtype

dtype('int16')

In [12]:
a.itemsize # gives the size of the item present in the array.

2

In [15]:
a.nbytes # gives the total size of the array occupied in the memory.
# 10 bytes as result since there are 5 elements with each 2 bytes.

10

In [18]:
a=np.arange(1,13).reshape(4,3)
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [17]:
a[0] # gives the first row here 

array([1, 2, 3])

In [20]:
a[:,2] # gives 2nd index column 

array([ 3,  6,  9, 12])

In [21]:
a[0,:] # same as a[0]

array([1, 2, 3])

In [23]:
a[0,1:6:2] # step size is 2 given here.

array([2])

In [27]:
a[0,::-1] 

array([3, 2, 1])

In [28]:
a[0,2::-1]  # start from index 2 and go in backward direction

array([3, 2, 1])

In [30]:
a[0,1::-1]  # start from index 1 and go in backward direction

array([2, 1])

In [31]:
a[1,2]=200

In [32]:
print(a)

[[  1   2   3]
 [  4   5 200]
 [  7   8   9]
 [ 10  11  12]]


In [33]:
a[:,2]=[3,4,5,6] # chaning all the 2nd index column values

In [34]:
print(a)

[[ 1  2  3]
 [ 4  5  4]
 [ 7  8  5]
 [10 11  6]]


In [37]:
a[1]=100 # entire 1st indexed row is changed here.

In [38]:
print(a)

[[  1   2   3]
 [100 100 100]
 [  7   8   5]
 [ 10  11   6]]


In [39]:
# suppose we have some other array with some shape and we want that array shape with all elements as 7

In [41]:
np.full_like(a,5) # here array 'a' have shape (4,3).we are making all elements with  5

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [42]:
np.full((3,4),10)

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [43]:
# np.random.rand () takes argument as shape only since it's range is already fixed with 0 and 1.

In [44]:
np.random.rand(4,7)

array([[0.29807936, 0.0429388 , 0.83471078, 0.84060013, 0.02582548,
        0.81712729, 0.27167233],
       [0.8598316 , 0.69783806, 0.69955543, 0.71649412, 0.15793443,
        0.03129022, 0.30206896],
       [0.16310092, 0.25863953, 0.5462794 , 0.09883193, 0.88561623,
        0.88010986, 0.55320294],
       [0.37514673, 0.37536186, 0.62736454, 0.9210233 , 0.9201919 ,
        0.56864913, 0.20249836]])

In [45]:
# if we want some other matrix shape then we need to give here as random_sample function.

In [47]:
np.random.random_sample(a.shape) # a shape takes place here.

array([[0.89623012, 0.30372376, 0.35314693],
       [0.82017886, 0.79568289, 0.58969144],
       [0.3060239 , 0.23471071, 0.7883595 ],
       [0.73055354, 0.79938834, 0.79064638]])

In [48]:
np.random.randint(7,size=(3,4)) # here the start value will be taken as 0 .

array([[5, 3, 1, 1],
       [1, 3, 3, 1],
       [3, 1, 4, 0]])

In [49]:
np.random.randint(3,77,size=(3,4))

array([[52, 20,  4, 36],
       [36, 61, 41, 49],
       [73, 75, 53, 58]])

In [50]:
# the identity matrix is by nature a square matrix. so only one argument is enough here.

In [51]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# repeat():
    1. suppose we want to repeat each element in the array some multiple times. we can use repeat()

In [52]:
np.repeat(a,3)

array([  1,   1,   1,   2,   2,   2,   3,   3,   3, 100, 100, 100, 100,
       100, 100, 100, 100, 100,   7,   7,   7,   8,   8,   8,   5,   5,
         5,  10,  10,  10,  11,  11,  11,   6,   6,   6])

In [53]:
a

array([[  1,   2,   3],
       [100, 100, 100],
       [  7,   8,   5],
       [ 10,  11,   6]])

In [54]:
np.repeat([1,2,3],5)

array([1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3])

In [56]:
np.repeat([[1,2,3]],5,axis=0) 

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [57]:
np.repeat([[1,2,3]],5,axis=1) 

array([[1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3]])

# https://www.sharpsightlabs.com/blog/numpy-axes-explained/ 
 1. understanding the axes concept is little bit tough here since it works in different way in different situations.
2. Go through the above link for clear understanding of the axis concept.

In [78]:
 a=np.ones((5,5))

In [84]:
# try to create a matrix with the required output . (5,5) matrix with all corners 1 and 9 in middle and remaining all zero.

In [85]:
a

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [86]:
a[1:3,1:4]=0

In [87]:
a

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [88]:
a[2,2]=9

In [83]:
a

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [90]:
# second way:

output=np.ones((5,5))
z=np.zeros((3,3))
z[1,1]=9
output[1:4,1:4]=z

In [92]:
output

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [93]:
b=a # this type of copying is like view()

In [95]:
## Linear Algebra
a=np.arange(2,8).reshape(3,2)
b=np.arange(4,10).reshape(2,3)

In [97]:
a*b # gives error when u multiply.

ValueError: operands could not be broadcast together with shapes (3,2) (2,3) 

In [98]:
a.dot(b) # matrix multiplication simply

array([[29, 34, 39],
       [51, 60, 69],
       [73, 86, 99]])

In [99]:
np.matmul(a,b) # matrix mutliplication

array([[29, 34, 39],
       [51, 60, 69],
       [73, 86, 99]])

# determinant

In [110]:
np.linalg.det(np.diag([91,2,3]))

546.0000000000001

In [113]:
np.diag((1,23,5))

array([[ 1,  0,  0],
       [ 0, 23,  0],
       [ 0,  0,  5]])

In [114]:
a=np.arange(2,18).reshape(4,4)

In [120]:
np.linalg.det(a)

3.662568488526098e-31

# stacking

In [121]:
v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])

In [123]:
np.vstack((v1,v2,v1,v2))

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [124]:
np.hstack((v1,v2,v1,v2))

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8])

#  Miscellaneous

In [188]:
f=open("data.txt","r") # u will work in pandas all these. right now just try to remember the functionality.

In [189]:
filedata=np.genfromtxt("data.txt",delimiter=",")

In [190]:
filedata.astype('int32')

array([   1,    2,    3,    4,    5,    6,    7,    8,    9,   12,    1,
        354,    3,    5,    3,    3,    5, 7654,   43,  876])

In [192]:
f=open("data.txt","r")
print(f)
for i in f:
    print(i)

<_io.TextIOWrapper name='data.txt' mode='r' encoding='cp1252'>
1,2,3,4,5,6,7,8,9,12,1,354,3,5,3,3,5,7654,43,876


# Boolean Masking and Advanced indexing 

In [129]:
a>10

array([[False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [130]:
a

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13],
       [14, 15, 16, 17]])

In [141]:
a[a>10] # we can give multiple conditions using logical operators.

array([], dtype=int32)

In [132]:
a=np.array([1,2,3,4,5,6,7,8])

In [133]:
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [138]:
a[[1,2,7]] # gives the elements present at the indexes 1,2,3

array([2, 3, 8])

In [139]:
np.any(a>5,axis=0)

True

In [140]:
np.all(a>5,axis=0)

False

# Questions

1.create an array with 1 t0 30 elements in 6*5 matrix

In [143]:
mat1=np.arange(1,31).reshape(6,5)

In [144]:
mat1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [146]:
mat1[2:4,0:2]

array([[11, 12],
       [16, 17]])

In [149]:
mat1[[0,1,2,3],[1,2,3,4]] # try to understand very carefully here.

array([ 2,  8, 14, 20])

In [150]:
mat1[[0],[1,2,3,4]]

array([2, 3, 4, 5])

In [156]:
mat1[[0,4,5],3:] # very important concept.

array([[ 4,  5],
       [24, 25],
       [29, 30]])