# lec 1
## what is numpy in python

1. Numpy is the fundamental package for scientific computing in Python.
2. It is a python library that provides a multidimensional array object,various derived objects.

# Array
1. An array is a grid of values and it contains information about the raw data ,how to locate an element and how to interpret an element.

# Arrays over lists
1. consumes less memory
2. fast as compared to python list
3. convenient to use



In [1]:
# list--> [1,2,3,4,5]
# array--> [1 2 3 4 5] here no commas present

In [2]:
import numpy as np
x=np.array([1,2,3,4,5])
print(x)

[1 2 3 4 5]


In [3]:
type(x)

numpy.ndarray

# Importance of Numpy in Python
1. wide variety of mathematical operations on arrays
2. It supplies an enormous library of high level mathematical functions that operate on these arrays and matrices.
3. Mathematical,logical,shape manipulation,sorting,selecting,I/O,discrete fourier transfoems,basic linear algebra,basic statistical operations,random simulation and much more.

# lec 2
## Arrays vs Pythin lists

In [10]:
# %timeit gives time taken to execute one line
# %%timeit gives time taken to execute whole program
%timeit [j**4 for j in range(1,9)]    # gives time taken to create the list  

4.78 µs ± 942 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [11]:
%timeit np.arange(1,9)**4

3.13 µs ± 620 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [12]:
# observe that time taken to create the array is less compared to the list 

# lec 3
## How to create numpy array

In [14]:
# to create a numpy array, we can use the function np.array()

In [15]:
import numpy as np
a=np.array([1,2,3])
print(a)

[1 2 3]


In [18]:
a=np.array([1,2,3,"phani"]) # treats every element as string only if even one single string is present.
print(a)

['1' '2' '3' 'phani']


In [19]:
type(a[0])

numpy.str_

In [20]:
print(type(a))

<class 'numpy.ndarray'>


In [21]:
l=[]
for i in range(1,5):
    x=int(input("enter the number:"))
    l.append(x)
print(np.array(l))

enter the number:5
enter the number:3
enter the number:2
enter the number:2
[5 3 2 2]


In [ ]:
# ndim gives the no of dimensions of the array

In [26]:
print(a.ndim)

1


In [32]:
ar2=np.array([[1,2,3,4],[1,2,3,8]]) # list inside a list

In [33]:
ar2

array([[1, 2, 3, 4],
       [1, 2, 3, 8]])

In [34]:
ar3=np.array([[1,2,3,4],[1,2,8]])

C:\Users\Phanindra Reddy\AppData\Local\Temp\ipykernel_13344\388830972.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  ar3=np.array([[1,2,3,4],[1,2,8]])


In [35]:
print(ar2.ndim)

2


In [37]:
ar4=np.array([[[1,2,3,4],[5,6,7,8],[3,4,5,6]]]) # firt 3 [[[ says it is 3dimensionsal

In [38]:
ar4

array([[[1, 2, 3, 4],
        [5, 6, 7, 8],
        [3, 4, 5, 6]]])

In [40]:
print(ar4.ndim)

3


In [42]:
ar5=np.array([1,2,3,4,5],ndmin=4) # creates a 4 dimensional array

In [43]:
ar5

array([[[[1, 2, 3, 4, 5]]]])

In [44]:
print(ar5.ndim)

4


# lec 4
## how to create numpy array using Numpy

# create an array of zeros

In [47]:
a=np.zeros((4,3))

In [48]:
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [49]:
a=np.zeros(4) # single dimension array

In [50]:
a

array([0., 0., 0., 0.])

In [51]:
print(a)

[0. 0. 0. 0.]


In [52]:
a.ndim

1

# create an array of ones's

In [54]:
arr1=np.ones(5)

In [55]:
arr1

array([1., 1., 1., 1., 1.])

In [56]:
print(arr1)

[1. 1. 1. 1. 1.]


In [60]:
print(np.ones((8,4)))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


# Empty array

In [63]:
print(arr1)

[1. 1. 1. 1. 1.]


In [67]:
arr2=np.empty((4,3))

In [69]:
arr2 # in previous memory whatever present we get as result 

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [70]:
arr3=np.empty(3)

In [71]:
arr3

array([1.21301975e-311, 0.00000000e+000, 9.91011138e+030])

# Range Function

In [74]:
arr1=np.arange(5)

In [75]:
arr1

array([0, 1, 2, 3, 4])

# Identity matrix--> diagonal elements filled with 1's

In [76]:
d1=np.eye(3)

In [77]:
d1

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [78]:
print(d1)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [79]:
d1=np.eye(3,5)

In [80]:
d1

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

## create an array with values that are spaced linearly in a specified interval

In [81]:
a1=np.linspace(1,3,20)

In [83]:
a2=np.linspace(0,10,num=5)

In [82]:
a1

array([1.        , 1.10526316, 1.21052632, 1.31578947, 1.42105263,
       1.52631579, 1.63157895, 1.73684211, 1.84210526, 1.94736842,
       2.05263158, 2.15789474, 2.26315789, 2.36842105, 2.47368421,
       2.57894737, 2.68421053, 2.78947368, 2.89473684, 3.        ])

In [84]:
print(a2)

[ 0.   2.5  5.   7.5 10. ]


# lec 5
## How to create Numpy arrays with random numbers

1. rand():  the function used to generate a random value b/w 0 to 1 
2. randn(): the function used to generate a random value close to zero. This may return positive or negative numbers as well.
3. ranf(): the function for doing random sampling in numpy.It returns an array of specified shape and fills it with random floats in the half open interval [0.0,1.0)

In [86]:
a1=np.random.rand(4) # 4 values in 1d array and all are in 0 to 1

In [87]:
a1

array([0.48505793, 0.31842711, 0.63102344, 0.66025741])

In [88]:
a2=np.random.rand(6,5)

In [89]:
a2

array([[0.83235532, 0.6125554 , 0.93091466, 0.02168811, 0.67268346],
       [0.25735336, 0.74475153, 0.72701496, 0.9785963 , 0.48886835],
       [0.6508311 , 0.76045847, 0.91565693, 0.33268929, 0.17393834],
       [0.02924871, 0.58901887, 0.46127159, 0.54077555, 0.80984689],
       [0.77068876, 0.04317409, 0.06211384, 0.79485213, 0.59522454],
       [0.62518748, 0.30403675, 0.04778807, 0.75656417, 0.42243808]])

In [90]:
a3=np.random.randn(4)

In [91]:
a3

array([ 1.02160476, -1.26769463, -0.65262735,  1.06043365])

# ranf()

In [92]:
a5=np.random.ranf(6)

In [93]:
a5

array([0.49619251, 0.36109727, 0.62322485, 0.0459753 , 0.3647439 ,
       0.54075882])

In [95]:
a6=np.random.ranf(6,4)

TypeError: random_sample() takes at most 1 positional argument (2 given)

#  randint()
1. The function is used to generate a random number between a given range.

In [97]:
a7=np.random.randint(1,8,4)

In [98]:
a7

array([7, 6, 4, 2])

In [99]:
a8=np.random.randint(1,8,(4,3))

In [100]:
a8

array([[7, 6, 6],
       [3, 1, 1],
       [2, 7, 3],
       [2, 5, 7]])