# lec 6
## Accessing elements of ndarray in numpy

In [2]:
import numpy as np
a=np.array([1,2,3,4,5])

In [3]:
print(a)

[1 2 3 4 5]


In [4]:
a[0]

1

In [5]:
a[-1]

5

In [6]:
a[1:3]

array([2, 3])

In [21]:
a=np.array([[1,2,3],[4,5,6],[5,6,7]])

In [22]:
print(a)

[[1 2 3]
 [4 5 6]
 [5 6 7]]


In [23]:
a[0,1] 

2

In [24]:
a[0][1]

2

In [27]:
a[-1][-2]
# -1 means last  1D array  and -2 means  in it the last second element

6

In [28]:
a=np.array([[[1,2,3],[4,5,6],[5,6,7]],[[11,12,13],[14,15,16],[15,16,17]]])

In [29]:
print(a)

[[[ 1  2  3]
  [ 4  5  6]
  [ 5  6  7]]

 [[11 12 13]
  [14 15 16]
  [15 16 17]]]


In [30]:
a[0,2,1]

6

In [31]:
a[1,2,2]

17

In [32]:
a[-1,-2,0]

14

# lec 7
## slicing operation on the ndarray in python

In [66]:
a=np.array([1,2,3,4,5])

In [67]:
a[:] # here 0 and length of array are default values

array([1, 2, 3, 4, 5])

In [36]:
a[::]

array([1, 2, 3, 4, 5])

In [71]:
a[-1::-1] # printing the array in reverse order
# start from -1 and print in the reverse order here.
# see in the result the difference between indexes is -1.

array([5, 4, 3, 2, 1])

In [70]:
a[::-1]  # here - indicates to print in reverse direction here.

array([5, 4, 3, 2, 1])

In [39]:
a[1:5] # 1,2,3,4 index values are the output here.

array([2, 3, 4, 5])

In [41]:
a[0:4] # excludes the stop index here.

array([1, 2, 3, 4])

In [43]:
a[0:4:2] # the difference between indexes should be 2 i.e, 0 2 4 6 8 ...

array([1, 3])

In [44]:
a[1:3]

array([2, 3])

In [45]:
a[:4]

array([1, 2, 3, 4])

In [46]:
a[2:]

array([3, 4, 5])

# 2D array slicing

In [64]:
a=np.array([[1,2,3],[4,5,6],[5,6,7]])

In [48]:
print(a)

[[1 2 3]
 [4 5 6]
 [5 6 7]]


In [65]:
a[-1::-1] 

array([[5, 6, 7],
       [4, 5, 6],
       [1, 2, 3]])

In [52]:
a[0,0:2] # array at 0th index and then first two elements of 0th array

array([1, 2])

In [53]:
a[1,1:3]

array([5, 6])

In [57]:
a[0:2,1:3] # first two rows and then second two columns
# first 0:2 means consider both the 0 th and 1 st arrays here. 
# and from both arrays here we need to take elements from 1:3 means elements at indices 1 and 2.

array([[2, 3],
       [5, 6]])

# 3D array slicing

In [72]:
a=np.array([[[1,2,3],[4,5,6],[5,6,7]],[[11,12,13],[14,15,16],[15,16,17]]])


In [59]:
# A 3D array is a array of 2D arrays 
print(a)

[[[ 1  2  3]
  [ 4  5  6]
  [ 5  6  7]]

 [[11 12 13]
  [14 15 16]
  [15 16 17]]]


In [62]:
a[0,1,0:2] # in first 0th  2D array index  matrix, in first index 1D array first two elements.

array([4, 5])

In [63]:
a[1,2,0:3]

array([15, 16, 17])

In [74]:
a[1,1,-1::-1]

array([16, 15, 14])

In [76]:
a[0:2,0:2,0:2]

array([[[ 1,  2],
        [ 4,  5]],

       [[11, 12],
        [14, 15]]])

# lec 8
## understanding of axis attribute in Numpy

1. If axis=0, then operations will be done on column wise
2. if axis=1, then operations will be done on row wise.


In [81]:
a=np.array([[20,43,62,10],[89,15,32,44]])

In [82]:
print(a)

[[20 43 62 10]
 [89 15 32 44]]


In [84]:
np.sort(a,axis=0) # here the sorting is done based on column wise .
# see the result here 15 and 43 sorted in the first index column and 32 and 62 are sorted in the column wise in second index  column 

array([[20, 15, 32, 10],
       [89, 43, 62, 44]])

In [86]:
np.sort(a,axis=1) # row wise we sorted the elements here.

array([[10, 20, 43, 62],
       [15, 32, 44, 89]])

# lec 9
## Data types copy (), view() inn numpy

# Data types 
1. i --> int   integer array
2. f --> float float array
3. S --> string
4. U --> unicode strings
5. m -->timedelta
5. M --> datetime
6. O --> Object
7. V --> void 

 1. dtype is the attribute which is used to represent the datatype of an array.
    

In [89]:
a.dtype

dtype('int32')

In [90]:
# we can also give the datatype whatever we want. it is optional.
a=np.array([1,2,3,4,5],dtype=bool)

In [91]:
print(a)

[ True  True  True  True  True]


In [94]:
a=np.array([1,2,3,4,5],dtype="U") # converts into string elements.. unicode strings

In [93]:
print(a)

['1' '2' '3' '4' '5']


In [95]:
a=np.array([1,2,3,4,5],dtype="f")

In [96]:
print(a)

[1. 2. 3. 4. 5.]


 # astype:
    
1. An external function which we can use to convert from one datatype to another datatype

In [97]:
x=a.astype("i") # integer type

In [98]:
x

array([1, 2, 3, 4, 5], dtype=int32)

In [99]:
x=np.array(["10","20","30"]).astype("i")

In [100]:
x

array([10, 20, 30], dtype=int32)

# copy():
1. creates an external copy here
2. if any one of the element is modified , it won't reflect in the original array.
3. two arrays will be present here since external copy will be generated.

# view():
 1. creates a reference of the array.
 2. if any one element is modified then the original array also get's modified here.
 3. only one array is present ,since the reference is being used here.


In [101]:
a=np.array([[20,43,62,10],[89,15,32,44]])
print(a)

[[20 43 62 10]
 [89 15 32 44]]


In [122]:
c=a.copy()

In [123]:
print(c)

[[   20    43 70000    10]
 [   89    15    32    44]]


In [125]:
print(c.base) # if it is having own array, it returns None

None


In [126]:
print(b.base) # returns the array since b doesn't have any own array

[[   20    43 70000    10]
 [   89    15    32    44]]


In [104]:
c[0,1]=1000

In [105]:
print(c)
print(a)

[[  20 1000   62   10]
 [  89   15   32   44]]
[[20 43 62 10]
 [89 15 32 44]]


In [127]:
b=a.view() # b is taking reference and it doesn't have an array.

In [107]:
print(b)

[[20 43 62 10]
 [89 15 32 44]]


In [108]:
b[0,2]=70000

In [109]:
print(b)
print(a)

[[   20    43 70000    10]
 [   89    15    32    44]]
[[   20    43 70000    10]
 [   89    15    32    44]]


In [117]:
x=np.array(["10","20","30"])

In [118]:
x.dtype # here U2 represents as Unicode string with 2 bytes 

dtype('<U2')

In [119]:
x=np.array(["10","20","300"])

In [120]:
x.dtype # since 100 here will be represented in 3 bytes,so for every item takes 3 bytes

dtype('<U3')

# lec 10
## joining arrays(concatenate,stack,vstack,hstack,staack in Numpy)

In [150]:
import numpy as np
a1=np.arange(1,17).reshape(4,4)
a2=np.arange(3,19).reshape(4,4)
print(a1)
print()
print(a2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]
 [15 16 17 18]]


In [151]:
np.concatenate((a1,a2))
# column wise  # all first columns will come in a single line

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [ 3,  4,  5,  6],
       [ 7,  8,  9, 10],
       [11, 12, 13, 14],
       [15, 16, 17, 18]])

In [152]:
np.concatenate((a1,a2),axis=1)  # row wise
# all first rows will come in a single line.

array([[ 1,  2,  3,  4,  3,  4,  5,  6],
       [ 5,  6,  7,  8,  7,  8,  9, 10],
       [ 9, 10, 11, 12, 11, 12, 13, 14],
       [13, 14, 15, 16, 15, 16, 17, 18]])

In [153]:
np.stack((a1,a2)) # see here two 2D dimensional arrays are present.

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]],

       [[ 3,  4,  5,  6],
        [ 7,  8,  9, 10],
        [11, 12, 13, 14],
        [15, 16, 17, 18]]])

In [154]:
np.stack((a1,a2),axis=1) # row wise stack

array([[[ 1,  2,  3,  4],
        [ 3,  4,  5,  6]],

       [[ 5,  6,  7,  8],
        [ 7,  8,  9, 10]],

       [[ 9, 10, 11, 12],
        [11, 12, 13, 14]],

       [[13, 14, 15, 16],
        [15, 16, 17, 18]]])

In [156]:
a1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [157]:
a2

array([[ 3,  4,  5,  6],
       [ 7,  8,  9, 10],
       [11, 12, 13, 14],
       [15, 16, 17, 18]])

In [159]:
np.vstack((a1,a2)) # same like concatenate 

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [ 3,  4,  5,  6],
       [ 7,  8,  9, 10],
       [11, 12, 13, 14],
       [15, 16, 17, 18]])

In [160]:
np.hstack((a1,a2))

array([[ 1,  2,  3,  4,  3,  4,  5,  6],
       [ 5,  6,  7,  8,  7,  8,  9, 10],
       [ 9, 10, 11, 12, 11, 12, 13, 14],
       [13, 14, 15, 16, 15, 16, 17, 18]])

In [161]:
np.dstack((a1,a2))

array([[[ 1,  3],
        [ 2,  4],
        [ 3,  5],
        [ 4,  6]],

       [[ 5,  7],
        [ 6,  8],
        [ 7,  9],
        [ 8, 10]],

       [[ 9, 11],
        [10, 12],
        [11, 13],
        [12, 14]],

       [[13, 15],
        [14, 16],
        [15, 17],
        [16, 18]]])