# lec 11
## Splitting array(split(),array_split(),vsplit(),hsplit()) in Numpy

In [3]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9,10])

In [4]:
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [5]:
np.split(a,5) # splitting 1D array into multiple 1D arrays here.

[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8]), array([ 9, 10])]

In [6]:
np.split(a,2)

[array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10])]

In [9]:
np.split(a,3) # gives error since equal no of division is not possible here.

ValueError: array split does not result in an equal division

In [12]:
np.array_split(a,3) # starts adjusting the elements from last element . 
# first it will try to arrange from the last element here.

[array([1, 2, 3, 4]), array([5, 6, 7]), array([ 8,  9, 10])]

In [13]:
np.array_split(a,4)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8]), array([ 9, 10])]

In [14]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
np.hsplit(a,2)

[array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10])]

In [16]:
np.vsplit(a,2) # works only if the dimension is more than 1 

ValueError: vsplit only works on arrays of 2 or more dimensions

In [17]:
b=np.array([[1,2,3],[4,5,6]])

In [18]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
np.vsplit(b,2)

[array([[1, 2, 3]]), array([[4, 5, 6]])]

In [21]:
np.vsplit(b,3) # equal diisions should be possible here else error occurs .

ValueError: array split does not result in an equal division

# lec 12
## search in Numpy ( where() and searchsorted())

#where()

In [23]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
np.where(a>6)

(array([6, 7, 8, 9], dtype=int64),)

In [25]:
np.where(a==9)

(array([8], dtype=int64),)

In [27]:
np.where(a==100) # returns an empty array if condition doesn't satisfy here.

(array([], dtype=int64),)

In [28]:
np.where(a%3==0)

(array([2, 5, 8], dtype=int64),)

In [29]:
searchsorted():
     This will implement the binary search here and returns the index where the specified value should be inserted.
     Elements should be in sorted order here for binary search.
     
     

SyntaxError: invalid syntax (2130165236.py, line 1)

In [31]:
np.searchsorted(a,2.5) #  it will try to sort in a order that it  should not be disturb order here.

2

In [33]:
np.searchsorted(a,[2.5,4.5,7.5])

array([2, 4, 7], dtype=int64)

# lec 13
## sort() in Numpy

1. By default, this will uses a quick sort technique here.
2. Parameters are array ,axis(default is -1),kind [quick/merge],order. kind is optional


In [34]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [35]:
np.sort(a)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [36]:
a1=np.array([3,2,6,7,8,4,5,6,9,3,46,23,78,213,321,4,78,9])

In [37]:
np.sort(a1)

array([  2,   3,   3,   4,   4,   5,   6,   6,   7,   8,   9,   9,  23,
        46,  78,  78, 213, 321])

In [40]:
a2=np.array([[3,1,2],[4,7,2]])

In [41]:
np.sort(a2)

array([[1, 2, 3],
       [2, 4, 7]])

In [44]:
np.sort(a2,axis=0) 
# all the elements should be less in axis 0 when compared to axis 1 
# try to search for more proper explanation here or watch the video again.

array([[3, 1, 2],
       [4, 7, 2]])

In [59]:
np.sort(a2,axis=1)

array([[1, 2, 3],
       [2, 4, 7]])

In [46]:
b=np.array([[50,40,30],[10,20,60]])

In [47]:
print(b)

[[50 40 30]
 [10 20 60]]


In [49]:
np.sort(b,axis=0) 
  # first 10 will be search with above 50 40 30 .since 10 is less than 50 both swaps here.
# next 20 will be search with 10 40 30 (swapped one). since 20 is less than 40 ,both swaps here.
# since 60 is less than 10 20 30 ,no swapping takes place here.

array([[10, 20, 30],
       [50, 40, 60]])

1. we can create the fields here with names and their types by using dtype function.
2. for ex- a name field with the string type and percentage field with float type here.
3. dtype([('name','S10'),('perc',float)])
4. we created two fields here. one with the name and other with the percentage here.

In [56]:
d=np.dtype([('name','S10'),('perc',float)]) # these are the fields . one with name field and another with  perc fields
# based on these fields we can also sort here in the order parameter.
stud=np.array([("indra",90.3),("lucky",56.7),("venky",96.3)],dtype=d)
stud

array([(b'indra', 90.3), (b'lucky', 56.7), (b'venky', 96.3)],
      dtype=[('name', 'S10'), ('perc', '<f8')])

In [57]:
np.sort(stud,order="name")

array([(b'indra', 90.3), (b'lucky', 56.7), (b'venky', 96.3)],
      dtype=[('name', 'S10'), ('perc', '<f8')])

In [58]:
np.sort(stud,order="perc")

array([(b'lucky', 56.7), (b'indra', 90.3), (b'venky', 96.3)],
      dtype=[('name', 'S10'), ('perc', '<f8')])

# lec 14
## Arithmetic Operations on Arrays in Numpy

# Broadcast rules
1. The order (shape)of two arrays must be equal to perform addition, subtraction.[element to element operation here]
2. The second array should have atleast one dimension and the number of elements in that dimension should be equal to the first    array. If a has shape (3,3) and if b has (3,) shape then also we can perform the operations here.
3.  if seocnd array having single element, then also we can apply the operations on the arrays.

In [61]:
a=np.array([[1,2],[3,4]])
b=np.array([2,3])

In [62]:
a.shape

(2, 2)

In [63]:
b.shape

(2,)

In [86]:
# rule no 3
c=np.array([2]) # here now when performing broadcasting all the elements are treated as 2 with the shape(2,2)

In [83]:
c.shape

(1,)

In [84]:
a+c

array([[3, 4],
       [5, 6]])

In [87]:
np.subtract(a,c)

array([[-1,  0],
       [ 1,  2]])

In [68]:
# here we can  perform the operations between a and b.
# for b , the interpreter will copy the same elements into one more dimension as [2,3] as [[2,3],[2,3]]
# b is having one dimension and the number of elements are equal then the interpreter will treats it as [2 3] [2 3]-> now the shape is (2,2) for b also.

In [66]:
a+b # see here the result.

array([[3, 5],
       [5, 7]])

In [67]:
a-b

array([[-1, -1],
       [ 1,  1]])

In [69]:
# for rule 3, if it is having the single element, then it copies the entire array with that element only

In [71]:
arr1=np.arange(1,10).reshape(3,3)
arr2=np.arange(3,12).reshape(3,3)
np.add(arr1,arr2)

array([[ 4,  6,  8],
       [10, 12, 14],
       [16, 18, 20]])

In [72]:
np.subtract(arr1,arr2)

array([[-2, -2, -2],
       [-2, -2, -2],
       [-2, -2, -2]])

In [73]:
np.multiply(arr1,arr2)

array([[ 3,  8, 15],
       [24, 35, 48],
       [63, 80, 99]])

In [74]:
np.divide(arr1,arr2)

array([[0.33333333, 0.5       , 0.6       ],
       [0.66666667, 0.71428571, 0.75      ],
       [0.77777778, 0.8       , 0.81818182]])

In [75]:
np.mod(arr1,arr2)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)

In [77]:
np.mod(arr1,3) # we can give a value here

array([[1, 2, 0],
       [1, 2, 0],
       [1, 2, 0]], dtype=int32)

In [78]:
np.power(arr1,arr2)

array([[         1,         16,        243],
       [      4096,      78125,    1679616],
       [  40353607, 1073741824, 1316288537]], dtype=int32)

In [80]:
np.power(arr1,3)

array([[  1,   8,  27],
       [ 64, 125, 216],
       [343, 512, 729]], dtype=int32)

In [81]:
# np.real(array) gives all the real parts of the array
# np.imag(array) gives all the imaginary parts of the array.
# np.conjugate(array) # changes the sign of the complex numbers.


In [89]:
np.reciprocal(arr1)

array([[1, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [90]:
f=np.array([0.3,4.3,0.5,0.6])

In [91]:
np.reciprocal(f)

array([3.33333333, 0.23255814, 2.        , 1.66666667])

In [92]:
c=np.array([3+5j,4+7j,5-9j])

In [93]:
print(c)

[3.+5.j 4.+7.j 5.-9.j]


In [95]:
print(np.real(c))

[3. 4. 5.]


In [97]:
print(np.imag(c))

[ 5.  7. -9.]


In [98]:
print(np.conjugate(c))

[3.-5.j 4.-7.j 5.+9.j]


 # lec 15
## statistical functions(mean,median,variance,standard deviation) in Numpy

1. amin(): we can find the minimum element along the axis(0/1) or in the complete array.
2. amax(): maximum element 

In [13]:
import numpy as np
a=np.array([[10,20,30,32,45,67,123,98765,34,23456],[12,34,56,23,123,34,5,6,7,8]])

In [14]:
print(a)

[[   10    20    30    32    45    67   123 98765    34 23456]
 [   12    34    56    23   123    34     5     6     7     8]]


In [15]:
np.max(a)

98765

In [16]:
np.min(a)

5

In [17]:
np.amax(a)

98765

In [18]:
np.amin(a)

5

In [20]:
np.amin(a,axis=0) # gives minimum elements array along the column wise

array([10, 20, 30, 23, 45, 34,  5,  6,  7,  8])

In [22]:
np.amax(a,axis=1) # gives maximum elements along the row wise.

array([98765,   123])

In [23]:
np.mean(a)

6144.5

In [24]:
np.average(a)

6144.5

In [25]:
np.median(a)

33.0

In [26]:
np.std(a)

21851.382339568358

In [30]:
# weighted average . refer youtube once .watch again this concept here.
# here w means 2 1D arrays are present.so we have to give 1,1 as weights.
w=[1,2]
np.average(a,weights=w,axis=0)

array([1.13333333e+01, 2.93333333e+01, 4.73333333e+01, 2.60000000e+01,
       9.70000000e+01, 4.50000000e+01, 4.43333333e+01, 3.29256667e+04,
       1.60000000e+01, 7.82400000e+03])

In [31]:
b=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [32]:
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [34]:
w=[1,2,3]
np.average(b,weights=w,axis=0)

# 1*1+4*2+7*3  / 1+2+3 --> 5.0  here  1 st column of b multiplying 'w' vector elements here

array([5., 6., 7.])

In [35]:
w=[1,1,1]
np.average(b,weights=w,axis=1) # here row wise we wil calculate the weighted average.

array([2., 5., 8.])

In [37]:
np.mean(b,axis=0) # column wise mean we will get here.

array([4., 5., 6.])

In [39]:
np.mean(b,axis=1) # row wise mean we will calculate here.

array([2., 5., 8.])

In [40]:
np.median(a)

33.0

In [41]:
np.median(b,axis=0)

array([4., 5., 6.])

In [43]:
np.var(a)

477482910.15

In [44]:
np.std(a)

21851.382339568358

In [45]:
np.var(b,axis=0)

array([6., 6., 6.])