# lec 6
## what is datatype of numpy array ?

1. uint8 -->unsigned integer (0 to 255) --> similarly we have uint6,uint32 and uint64.
2. bool_ --> boolean(True or False) stored as a byte.
3. float_  --> short hand for float 64  . underscore is there.
4. complex --> for complex values.
5. complex64 --> represented by two 32-bit floats (real and imaginary components.)
6. complex128 --> complex number,represented by two 64-bit floats (real and imaginary components.)
7. complex_  --> shorthand for complex128


In [1]:
import numpy as np
var=np.array([1,2,3,4,5],dtype=complex)

In [2]:
var

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j])

In [3]:
var.dtype

dtype('complex128')

In [12]:
var1=np.array([1,2,3,4,5],dtype=float)

In [13]:
var1

array([1., 2., 3., 4., 5.])

In [6]:
var=np.array(["s","f","k","u"])
var.dtype

dtype('<U1')

In [7]:
var=np.array(["s","f","k","u",1,2,3,4])

In [9]:
var.dtype

dtype('<U11')

In [10]:
# m --> time delta
# O --> object
# V --> The fixed chunk of memory for other types(void)

In [15]:
np.int32(var1)
# we can convert from one datatype to another datatype using the np.datatype(array)

array([1, 2, 3, 4, 5])

In [16]:
x=np.array([1,2,3,4,5])
x.dtype

dtype('int32')

In [18]:
y=np.int8(x)

In [19]:
y

array([1, 2, 3, 4, 5], dtype=int8)

In [23]:
# by using single characters in dtype, we can represent the datatype.
x1=np.array([1,2,3,4],dtype="f") 
print(x1.dtype)

float32


# lec 7
##  What are Numpy Arithmetic Operations

In [1]:
# np.power(a,b) # calculates power 
# np.reciprocal(a) # calculates the reciprocal of the each element.

In [3]:
import numpy as np
np.reciprocal([0,1])

C:\Users\Phanindra Reddy\AppData\Local\Temp\ipykernel_7760\101735022.py:2: RuntimeWarning: divide by zero encountered in reciprocal
  np.reciprocal([0,1])
C:\Users\Phanindra Reddy\AppData\Local\Temp\ipykernel_7760\101735022.py:2: RuntimeWarning: invalid value encountered in reciprocal
  np.reciprocal([0,1])


array([-2147483648,           1], dtype=int32)

# lec 8
## What are Arithmetic functions in Numpy

In [4]:
# np.cumsum(arr)# gives the cummulative sum of the array.

In [5]:
a=np.arange(1,6)

In [6]:
a

array([1, 2, 3, 4, 5])

In [8]:
np.cumsum(a) # one by one element adding to each other here.

array([ 1,  3,  6, 10, 15], dtype=int32)

# lec 9
## Learn about shape and reshaping in Numpy arrays

In [10]:
# while initialising the array,we can set the dimension for the array.

In [17]:
a=np.array([1,2,3,4,5,6],ndmin=4)
# here ndmin is there. don't get confuse.

In [18]:
a

array([[[[1, 2, 3, 4, 5, 6]]]])

In [19]:
a.ndim

4

In [20]:
a.shape

(1, 1, 1, 6)

In [22]:
a.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
a.reshape(-1) # -1 helps to convert back to the original shape here.

array([1, 2, 3, 4, 5, 6])

# lec 10
##  Learn Broadcasting in Numpy arrays

In [25]:
# refer other channel videos

In [30]:
a=np.array([12,13,14]).reshape(1,3)
b=np.array([1,2,3]).reshape(3,1) # np.array([[1],[2],[3]])
print(a)
print()
print(b)

[[12 13 14]]

[[1]
 [2]
 [3]]


In [27]:
a+b

array([[13, 14, 15],
       [14, 15, 16],
       [15, 16, 17]])

In [28]:
b+a

array([[13, 14, 15],
       [14, 15, 16],
       [15, 16, 17]])

In [31]:
a

array([[12, 13, 14]])

In [32]:
a1=np.array([1,2,3,4])
print(a.shape)
print(a1.shape)

(1, 3)
(4,)


In [33]:
a+a1

ValueError: operands could not be broadcast together with shapes (1,3) (4,) 

# lec 11
## Explain indexing and Slicing in Numpy arrays in Python

In [34]:
# all concepts covered in the previous lectures only.

# lec 12
## Iterating Numpy Arrays

In [40]:
print(a) # see here a is a 2D array. for iterating 2D arrays, we need to use the nditer(). 
#entire 1D array is stored in a[0] itself

[[12 13 14]]


In [41]:
for i in a:
    print(i) # to get the element wise as output inn arrays we need to use nditer().
# above first it will search for first element , but here the first element is the whole 1D array itself. 

[12 13 14]


In [42]:
a[0] # see here 

array([12, 13, 14])

In [43]:
a.ndim

2

In [44]:
for i in np.nditer(a):
    print(i)

12
13
14


In [45]:
b=np.array([1,2,3])

In [46]:
print(b)

[1 2 3]


In [47]:
b.ndim

1

In [49]:
print(b[0]) # since dimension is 1 here, we are getting exact value here.

1


In [50]:
for j in b:
    print(j)

1
2
3


In [51]:
a

array([[12, 13, 14]])

In [53]:
a1=np.array([[1,2,3],[4,5,6]])
print(a1)

[[1 2 3]
 [4 5 6]]


In [56]:
# traditional way to iterate through the 2D array elements.
for i in a1:
    for j in i:
        print(j)
        
        
# if it is an 3D array, then we need to use one more for loop.

1
2
3
4
5
6


In [61]:
# to change to another data type while iterating, we need to give flags here to store the data type which going to change
# buffer will create an extra space here.
# we need to give operator data type here.
for i in np.nditer(a,flags=["buffered"],op_dtypes=["S"]):
    print(i)

b'12'
b'13'
b'14'


# ndenumerate

In [62]:
# this will give us both the index and the data present at the index value.

In [67]:
for index,data in np.ndenumerate(a1):
    print(index,"---->",data)

(0, 0) ----> 1
(0, 1) ----> 2
(0, 2) ----> 3
(1, 0) ----> 4
(1, 1) ----> 5
(1, 2) ----> 6


# lec 13
## Copy vs View Numpy Python

In [68]:
 # already covered in old videos

# lec 14
## Joining & split Numpy arrays using(concatenate,stack,aray_split)


In [71]:
a1=np.arange(1,5)
a2=np.arange(4,8)

In [76]:
print(np.concatenate((a1,a2))) # for 1D array
# this concatenate will results in a single dimension array as here dimension is 1 here.

[1 2 3 4 4 5 6 7]


In [77]:
np.stack((a1,a2))

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [78]:
a1=np.arange(1,5).reshape(2,2)
a2=np.arange(4,8).reshape(2,2)
print(np.concatenate((a1,a2),axis=1)) # it will give as [a1 a2] # along the single row wise the arrays are arranged 
# be careful that along the single row wise a1,a2 are arranged not the elements.
# axis=1 means forward direction

[[1 2 4 5]
 [3 4 6 7]]


In [80]:
print(np.concatenate((a1,a2),axis=0)) # it will give as [ a1
                                                      #    a2 ]
    # along the single column wise the arrays are arranged here.
    # axis=0 means downward direction.

[[1 2]
 [3 4]
 [4 5]
 [6 7]]


In [83]:
np.stack((a1,a2))

array([[[1, 2],
        [3, 4]],

       [[4, 5],
        [6, 7]]])

In [87]:
print(np.stack((a1,a2),axis=1))

[[[1 2]
  [4 5]]

 [[3 4]
  [6 7]]]


In [89]:
print(np.hstack((a1,a2))) # horizontally , which means along the row.

[[1 2 4 5]
 [3 4 6 7]]


In [90]:
print(np.vstack((a1,a2)))

[[1 2]
 [3 4]
 [4 5]
 [6 7]]


In [91]:
print(np.dstack((a1,a2)))  along the height 

[[[1 4]
  [2 5]]

 [[3 6]
  [4 7]]]


# splitting
 #### Splitting breaks one array into the multiple arrays.

In [93]:
a=np.array([1,2,3,4,6,3])
print(a)

[1 2 3 4 6 3]


In [94]:
print(np.array_split(a,3))

[array([1, 2]), array([3, 4]), array([6, 3])]


In [96]:
ar=np.array_split(a,3)
print(ar)

[array([[1, 2]]), array([[3, 4]]), array([[6, 3]])]


In [97]:
print(type(ar)) # see here it will give result as list.

<class 'list'>


In [98]:
print(ar[0])

[[1 2]]


In [99]:
print(type(ar[0]))

<class 'numpy.ndarray'>


In [100]:
# we can also give the parameters as axis=1 or axis=0.

In [106]:
a=np.array([1,2,3,4,6,3]).reshape(3,2)
print(a) 

[[1 2]
 [3 4]
 [6 3]]


In [107]:
np.array_split(a,2,axis=1)

[array([[1],
        [3],
        [6]]),
 array([[2],
        [4],
        [3]])]

In [109]:
np.array_split(a,2,axis=0) # it will split coming towars the downward direction.

[array([[1, 2],
        [3, 4]]),
 array([[6, 3]])]

# lec 15
## what are numpy array functions

Search Array:
    Search an array for a certain value,and return the indexes that get a match.

In [117]:
a=np.array([1,2,3,4,5,6,5,3,2,1,3,4,5,43,56])

In [118]:
np.where(a==6)

(array([5], dtype=int64),)

In [119]:
np.where(a%2==1)

(array([ 0,  2,  4,  6,  7,  9, 10, 12, 13], dtype=int64),)

# Search Sorted Array:
   Which performs a binary search in the array and returns the index where the specified value would be inserted to maintain the search order.

In [120]:
np.searchsorted(a,10 )# this will give the exact result when the array is sorted .

13

In [121]:
 # to perform sorting from right side, we need to give an extra parameter side="right"
np.searchsorted(a,10,side="right" )

13

# sort array

Sort Array: Ordered sequence is any sequence that has an order corresponding to elements like numeric or alphabetical,ascending or descending.

In [123]:
np.sort(a)

array([ 1,  1,  2,  2,  3,  3,  3,  4,  4,  5,  5,  5,  6, 43, 56])

In [124]:
a1

array([[1, 2],
       [3, 4]])

In [129]:
c=np.array([[1,2,6,3,21,67,34,21],[31, 24,34,65,78,33,5,12]])

In [130]:
np.sort(c)

array([[ 1,  2,  3,  6, 21, 21, 34, 67],
       [ 5, 12, 24, 31, 33, 34, 65, 78]])

# Filter array:
#### getting some elements out of an existing array and creating a new array out of them.

In [131]:
a>2 # to get filter,we need True and False

array([False, False,  True,  True,  True,  True,  True,  True, False,
       False,  True,  True,  True,  True,  True])

In [133]:
a[a>3] # wherever True,we get all the elements here.

array([ 4,  5,  6,  5,  4,  5, 43, 56])

# lec 16
## what are numpy array functions(part2)

In [135]:
a

array([ 1,  2,  3,  4,  5,  6,  5,  3,  2,  1,  3,  4,  5, 43, 56])

In [136]:
np.random.shuffle(a)

In [137]:
a

array([ 3,  2,  5,  1,  1,  3,  5, 43,  3, 56,  5,  4,  2,  6,  4])

In [138]:
np.unique(a)

array([ 1,  2,  3,  4,  5,  6, 43, 56])

In [139]:
np.unique(a,return_index=True)

(array([ 1,  2,  3,  4,  5,  6, 43, 56]),
 array([ 3,  1,  0, 11,  2, 13,  7,  9], dtype=int64))

In [142]:
np.unique(a,return_index=True,return_counts=True)

(array([ 1,  2,  3,  4,  5,  6, 43, 56]),
 array([ 3,  1,  0, 11,  2, 13,  7,  9], dtype=int64),
 array([2, 2, 3, 2, 3, 1, 1, 1], dtype=int64))

In [143]:
a.size

15

In [145]:
d=np.resize(a,(3,5))
print(d)

[[ 3  2  5  1  1]
 [ 3  5 43  3 56]
 [ 5  4  2  6  4]]


# Flatten and Ravel

In [146]:
d

array([[ 3,  2,  5,  1,  1],
       [ 3,  5, 43,  3, 56],
       [ 5,  4,  2,  6,  4]])

In [148]:
d.flatten() # it is like 

array([ 3,  2,  5,  1,  1,  3,  5, 43,  3, 56,  5,  4,  2,  6,  4])

In [149]:
d.ravel() # it is like view()

array([ 3,  2,  5,  1,  1,  3,  5, 43,  3, 56,  5,  4,  2,  6,  4])

In [150]:
d.flatten(order='F')

array([ 3,  3,  5,  2,  5,  4,  5, 43,  2,  1,  3,  6,  1, 56,  4])

In [151]:
e=d.flatten() # this will acts like copy()
print(e)


[ 3  2  5  1  1  3  5 43  3 56  5  4  2  6  4]


In [152]:
e[1]=1000

In [153]:
e

array([   3, 1000,    5,    1,    1,    3,    5,   43,    3,   56,    5,
          4,    2,    6,    4])

In [154]:
d

array([[ 3,  2,  5,  1,  1],
       [ 3,  5, 43,  3, 56],
       [ 5,  4,  2,  6,  4]])

In [157]:
f=d.ravel()
print(f)
f[0]=1000 # see here the original array is also got changed since we used ravel which acts like view() 
print(e)

[1000    2    5    1    1    3    5   43    3   56    5    4    2    6
    4]
[   3 1000    5    1    1    3    5   43    3   56    5    4    2    6
    4]


# lec 17
## what are Numpy Insert and Delete Arrays Functions

In [158]:
 a

array([ 3,  2,  5,  1,  1,  3,  5, 43,  3, 56,  5,  4,  2,  6,  4])

In [159]:
np.insert(a,3,500)

array([  3,   2,   5, 500,   1,   1,   3,   5,  43,   3,  56,   5,   4,
         2,   6,   4])

In [161]:
np.insert(a,(3,7,9),100000)  # at multiple indices,we are inserting a 1000000 value.

array([     3,      2,      5, 100000,      1,      1,      3,      5,
       100000,     43,      3, 100000,     56,      5,      4,      2,
            6,      4])

In [162]:
np.insert(a,3,[500,8990,568])

array([   3,    2,    5,  500, 8990,  568,    1,    1,    3,    5,   43,
          3,   56,    5,    4,    2,    6,    4])

In [164]:
np.insert(a,8,888.678) # we cannot insert the float values here. only integer values will be inserted here.

array([  3,   2,   5,   1,   1,   3,   5,  43, 888,   3,  56,   5,   4,
         2,   6,   4])

In [169]:
var1=np.array([[1,2,3],[4,5,6]])
v1=np.insert(var1,2,6,axis=0) # 

In [170]:
print(v1)

[[1 2 3]
 [4 5 6]
 [6 6 6]]


In [174]:
v2=np.insert(var1,2,6,axis=1)

In [175]:
print(v2)

[[1 2 6 3]
 [4 5 6 6]]


In [177]:
v3=np.insert(var1,2,[6,16],axis=1) # since only two rows we need to give 2 elements only.


In [178]:
print(v3)

[[ 1  2  6  3]
 [ 4  5 16  6]]


In [183]:
v4=np.insert(var1,2,[6,23,16],axis=0)  # since three columns are present ,we need to give 3 elements here.

In [184]:
print(v4)

[[ 1  2  3]
 [ 4  5  6]
 [ 6 23 16]]


In [185]:
a

array([ 3,  2,  5,  1,  1,  3,  5, 43,  3, 56,  5,  4,  2,  6,  4])

In [187]:
np.append(a,[100,300,43])

array([  3,   2,   5,   1,   1,   3,   5,  43,   3,  56,   5,   4,   2,
         6,   4, 100, 300,  43])

In [196]:
np.append(v4,[[100,29,34]],axis=0) # since v4 has dimension 2 ,we need to give append a 2D only.

array([[  1,   2,   3],
       [  4,   5,   6],
       [  6,  23,  16],
       [100,  29,  34]])

In [198]:
np.delete(v4,3) # 3rd indexed array is deleted

array([ 1,  2,  3,  5,  6,  6, 23, 16])

In [199]:
a

array([ 3,  2,  5,  1,  1,  3,  5, 43,  3, 56,  5,  4,  2,  6,  4])

In [202]:
np.delete(a,[4,6,5,1]) # at these positions the elements will be deleted here.

array([ 3,  5,  1, 43,  3, 56,  5,  4,  2,  6,  4])

# lec 18
# The concept of Matrix Numpy Arrays in Python

1. Matrix and Arrays concept are both so much different.
2. So only we confuses about the axis 0 and 1 by comparing to the matrix row and columns,


In [226]:
a1=np.matrix([[1,2,3],[4,5,6],[7,8,9]])
print(a1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [227]:
a2=np.matrix([[3,4,5],[8,7,6],[3,5,4]])
print(a2)

[[3 4 5]
 [8 7 6]
 [3 5 4]]


In [206]:
np.matmul(a1,a2)

matrix([[ 28,  33,  29],
        [ 70,  81,  74],
        [112, 129, 119]])

In [207]:
a1.dot(a2)

matrix([[ 28,  33,  29],
        [ 70,  81,  74],
        [112, 129, 119]])

In [209]:
a1*a2 # since both are matrcies, here it is also a matrix multiplication only.

matrix([[ 28,  33,  29],
        [ 70,  81,  74],
        [112, 129, 119]])

In [212]:
v1=np.array([[1,2,3],[4,5,6],[7,8,9]])
v2=np.array([[3,4,5],[8,7,6],[3,5,4]])
v1*v2 #element wise multiplication here.

array([[ 3,  8, 15],
       [32, 35, 36],
       [21, 40, 36]])

In [213]:
a1.T

matrix([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])

In [214]:
np.transpose(a2)

matrix([[3, 8, 3],
        [4, 7, 5],
        [5, 6, 4]])

In [218]:
np.swapaxes(a1,0,1) # swapping the axes.

matrix([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])

In [219]:
# inverse (a ^-1)
print(a1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [220]:
print(np.linalg.inv(a1))

[[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]


# power of a matrix

In [228]:
np.linalg.matrix_power(a1,2) # here for that value,it can be >0,<0,=0

matrix([[ 30,  36,  42],
        [ 66,  81,  96],
        [102, 126, 150]])

In [229]:
np.linalg.matrix_power(a1,0) # gives Identity matrix or unit matrix

matrix([[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]])

In [230]:
np.linalg.matrix_power(a1,-2)

matrix([[ 5.96302842e+31, -1.19260568e+32,  5.96302842e+31],
        [-1.19260568e+32,  2.38521137e+32, -1.19260568e+32],
        [ 5.96302842e+31, -1.19260568e+32,  5.96302842e+31]])

In [231]:
np.linalg.det(a1)

-9.51619735392994e-16