# lec1
## How to install Numpy

# lec 2
## Basics of Numpy(creation of ndarray)

1. Numerical Python.
2. Provides lot of functions to work in a domain of linear algebra,fourier transforms and matrices.
3. Provides functions related to arrays.
4. Creates an array called ndarray.
5. Working of ndarray is faster than list.

In [4]:
import numpy 
numpy.__version__ # gives the version present in the system.

'1.21.5'

1.To create an ndarray(array) we have to use array() and pass either list or tuple.

In [7]:
import numpy as np
a=np.array([1,2,3])
print(a)

[1 2 3]


In [11]:
d0=np.array(9)
print(d0) # 0D array

9


In [12]:
d1=np.array([1,2,3])
print(d1)

[1 2 3]


In [13]:
d2=np.array([[1,2,3],[3,4,5]])

In [14]:
print(d2)

[[1 2 3]
 [3 4 5]]


In [15]:
d1.ndim

1

In [16]:
d2.ndim

2

In [17]:
type(d2)

numpy.ndarray

# lec 3
## ASARRAY(),FROMBUFFER(),FROMITER() IN NUMPY(ARRAYS WITH EXISTING DATA)

In [2]:
import numpy as np
l1=[1,2,3,4]
np.asarray(l1,dtype="float",order="C")

array([1., 2., 3., 4.])

In [3]:
l1=[1,2,3,4]
np.asarray(l1,dtype="float",order="F")

array([1., 2., 3., 4.])

In [7]:
l2=[[1,2,3,4],[2,6,5,9]]
np.asarray(l2,dtype="float",order="C")

array([[1., 2., 3., 4.],
       [2., 6., 5., 9.]])

In [10]:
l2=[[1,2,3,4],[2,6,5,9]]
np.asarray(l2,dtype="float",order="F") # here we won't observe any change here.
# print all the elements using nditer.
# nditer() prints all the elements in 1D  array.

array([[1., 2., 3., 4.],
       [2., 6., 5., 9.]])

In [31]:
s=b"welcome"
np.frombuffer(s,dtype="S1",count=-1,offset=0)

array([b'w', b'e', b'l', b'c', b'o', b'm', b'e'], dtype='|S1')

In [19]:
a=np.array([10,20,30,40])


In [20]:
a

array([10, 20, 30, 40])

In [21]:
res=np.asarray(a,dtype="float",order="C")

In [22]:
print(res)

[10. 20. 30. 40.]


In [25]:
l2=[[1,2,3,4],[2,6,5,9]]
res1=np.asarray(l2,dtype="float",order="F") # here we won't observe any change here. 

In [26]:
print(res1)

[[1. 2. 3. 4.]
 [2. 6. 5. 9.]]


In [28]:
# print all the elements using nditer.
# nditer() prints all the elements in 1D  array.

for i in np.nditer(res1): # here we can observe the difference neatly.
    print(i)

1.0
2.0
2.0
6.0
3.0
5.0
4.0
9.0


In [30]:
l2=[[1,2,3,4],[2,6,5,9]]
res1=np.asarray(l2,dtype="float",order="C")
for i in np.nditer(res1): # here we can observe the difference neatly.
    print(i)

1.0
2.0
3.0
4.0
2.0
6.0
5.0
9.0


In [34]:
s=b"hello_world" # here b means which means this data will be stored in bytes format not as strings.
res=np.frombuffer(s,dtype="S1",count=5,offset=4)
print(res)

[b'o' b'_' b'w' b'o' b'r']


In [35]:
list1=[10,20,3,4,5,6,7,8]
d=np.fromiter(list1,dtype="S1",count=-1)

In [36]:
print(d)

[b'1' b'2' b'3' b'4' b'5' b'6' b'7' b'8']


# lec 4
## ARANGE(),LINSPACE(),LOGSPACE() IN NUMPY (ARRAYS WITH NUMERICAL RANGES)

In [5]:
import numpy as np
np.arange(1,12,2,dtype="float") # we given stepsize as 2. so the difference between the elements is 2.

array([ 1.,  3.,  5.,  7.,  9., 11.])

In [13]:
print(np.linspace(1,10,num=5,endpoint=True,retstep=True,dtype="float")) # here the stepsize is 2.25

(array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ]), 2.25)


In [14]:
print(np.linspace(1,10,5,endpoint=False,retstep=True,dtype="int"))

(array([1, 2, 4, 6, 8]), 1.8)


In [15]:
np.linspace(1,12,endpoint=True) # 50 values will be returned here since count is not given.

array([ 1.        ,  1.2244898 ,  1.44897959,  1.67346939,  1.89795918,
        2.12244898,  2.34693878,  2.57142857,  2.79591837,  3.02040816,
        3.24489796,  3.46938776,  3.69387755,  3.91836735,  4.14285714,
        4.36734694,  4.59183673,  4.81632653,  5.04081633,  5.26530612,
        5.48979592,  5.71428571,  5.93877551,  6.16326531,  6.3877551 ,
        6.6122449 ,  6.83673469,  7.06122449,  7.28571429,  7.51020408,
        7.73469388,  7.95918367,  8.18367347,  8.40816327,  8.63265306,
        8.85714286,  9.08163265,  9.30612245,  9.53061224,  9.75510204,
        9.97959184, 10.20408163, 10.42857143, 10.65306122, 10.87755102,
       11.10204082, 11.32653061, 11.55102041, 11.7755102 , 12.        ])

In [17]:
np.logspace(1,10,num=5,endpoint=False,base=2)

array([  2.        ,   6.96440451,  24.25146506,  84.44850629,
       294.06677888])

In [18]:
print(np.logspace(1,10,endpoint=True,base=2))

[   2.            2.27154434    2.57995685    2.9302432     3.32808868
    3.77995051    4.2931626     4.87605462    5.53808714    6.29000526
    7.14401294    8.1139711     9.21562258   10.46684767   11.88795431
   13.50200769   15.3352046    17.41729864   19.78208311   22.4679395
   25.51846045   28.98315726   32.91826347   37.3876476    42.46384973
   48.22925884   54.77745007   62.21470345   70.66172888   80.25562529
   91.15210586  103.52802526  117.58425012  133.54891916  151.681146
  172.27522466  195.66540611  222.2313233   252.40415277  286.67361283
  325.59591193  369.80277612  420.01170228  477.0376034   541.80603498
  615.3682172   698.91809669  793.81172479  901.5892669  1024.        ]


 # lec 5
## Initializing arrays in Numpy(zeros,ones,full,eye functions)

In [19]:
print(np.zeros((2,3)))

[[0. 0. 0.]
 [0. 0. 0.]]


In [20]:
np.zeros((2,3),dtype="int")

array([[0, 0, 0],
       [0, 0, 0]])

In [21]:
np.ones(3)

array([1., 1., 1.])

In [22]:
np.ones((3,4),dtype="int")

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [24]:
np.full((3,4),6)

array([[6, 6, 6, 6],
       [6, 6, 6, 6],
       [6, 6, 6, 6]])

In [32]:
np.eye(4,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [33]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [34]:
np.eye(3,dtype="int")

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [35]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [37]:
np.shape(a)

(3, 3)

In [38]:
np.reshape(a,(9,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [39]:
a.reshape(1,9) #we can aslo give this syntax here.

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [41]:
np.full(7,2) # seven elements with all 2 only.

array([2, 2, 2, 2, 2, 2, 2])