# lec 1
## Python for Data science Numpy Introduction

1. All theory is written in the note book.
2. very good introduction and nice deep lecture on why we need Numpy.

# lec 2
## List vs Numpy array

In [2]:
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])

In [3]:
a*b

array([ 4, 10, 18])

# dot product

In [6]:
# traditional python code to find the dot product
def dp(a,b):
    sum=0
    for i,j in zip(a,b):
        sum=sum+i*j
    print(sum)

In [7]:
dp(a,b)

32


In [9]:
# dot product for two vectors using numpy
# see in one single line ,we performed the dot product.
a.dot(b)

32

In [10]:
# here we will calculate the time taken to perform the dot product

In [14]:
from datetime import datetime
def dp(a,b):
    sum=0
    for i,j in zip(a,b):
        sum=sum+i*j
    print(sum)
    
before=datetime.now()
dp(a,b)
after=datetime.now()
print("time taken is :",after-before) # this will give very very less time in nano or micro seconds here.

32
time taken is : 0:00:00


In [29]:
from datetime import datetime
def dp(a,b):
    sum=0
    for i,j in zip(a,b):
        sum=sum+i*j
    #print(sum)
    
before=datetime.now()
for i in range(1000000):
    dp(a,b)
after=datetime.now()
print("time taken is :",after-before)

time taken is : 0:00:03.801199


In [31]:
# here we use numpy code for executing above code and we check the time taken for it.
before=datetime.now()
for i in range(1000000):
    np.dot(a,b)
after=datetime.now()
print("time taken is :",after-before) # this value will be less than the above value
# so performance wise,numpy code is so much better and fast.

time taken is : 0:00:03.234021


1. ARRAY is an indexed collection of homogeneous data elements .
2. Bydefault arrays concept is not available in Python, instead we can use list.
3. So to use arrays, we need Numpy.
4. List and array ,both are not same.

In [34]:
# we can also represent the arrays using the array module.
import array
a=array.array("i",[1,2,3,4]) # here i represents the int type array.

In [35]:
a

array('i', [1, 2, 3, 4])

In [37]:
# we won't use array module since we cannot expect much library support from it.

# Similarities between Python List and Numpy Array:

1. Both can be used to store the data.
2. The order will be prrserved in both types. Hence we can access the elements using index.
3. Slicing is also applicable for both.
4. Both are mutable,i.e, once we create list or array we can change its elements.


# Differences between Python List and Numpy Array:

1. List is inbuilt datatype but numpy array is not inbuilt. To use numpy arrays,we have to install and import numpy library explicitly.
2. Lists can hold heterogeneous elements whereas arrays can store only homogeneous elements.
3. On arrays we can perform vector operations( the operations which can be operated on every element of the array). But we cannot perform vector operations on list.
4. Arrays consume less memory compared to lists.
5. Arrays are superfast when compared with list.
6. Numpy arrays are more convenient to use to perform mathematical complex operations.

In [38]:
a=np.array([10,20,30])

In [39]:
print(a)

[10 20 30]


In [41]:
a+1 # we cannot use this operation on the list.

array([11, 21, 31])

In [43]:
a/2 # on every element the operation is getting performed.

array([ 5., 10., 15.])

In [45]:
l=[1,2,3,4,5]
a=np.array(l)
print(l)
print(a)

[1, 2, 3, 4, 5]
[1 2 3 4 5]


In [47]:
import sys
print(sys.getsizeof(l))
print(a.nbytes)

120
20


In [52]:
sys.getsizeof(l)

120

# lec 3
## Numpy Indexing

In [53]:
# itemsize: the size of each array element in bytes.

In [54]:
a

array([1, 2, 3, 4, 5])

In [56]:
a.shape # don't say here shape as 1*5 since it is not a 2D array.
# if it is 2D array then we can say it has shape(1,5)

(5,)

In [57]:
# if shape result is (6,), then that array has 1D with six elements in it.

# Data types in Numpy

In [59]:
a=np.array([1,2,3,4,5],dtype='i8')
# here i8 means not int 8 it means integer value with 8 bytes
a.dtype

dtype('int64')

In [60]:
b=np.array([1,2,3,4,5],dtype='int8')

In [61]:
b.dtype

dtype('int8')

In [67]:
c=np.array([1,2,3,4,5],dtype=int) # here we will get the default value.

In [68]:
c.dtype

dtype('int32')

In [69]:
c=np.array([1,2,3,4,5],dtype='i')

In [70]:
c.dtype

dtype('int32')

In [71]:
c

array([1, 2, 3, 4, 5], dtype=int32)

In [72]:
c.astype('float')

array([1., 2., 3., 4., 5.])

In [74]:
# we can also convert it using one more way here.
c1=np.float64(a)

In [75]:
c1

array([1., 2., 3., 4., 5.])

In [76]:
x=np.bool_(a)

In [77]:
x

array([ True,  True,  True,  True,  True])

# lec 4
## Numpy Slicing

1. If the step value is negative,we have to consider elements from begin to end+1 in backward direction.(right to left)


In [64]:
ar1=np.array([4,5,6,7,9,4,3,22,2,5,6,7])

In [65]:
ar1[0:6]

array([4, 5, 6, 7, 9, 4])

In [66]:
ar1[5:1:-1] # begin to end +1 means 5 to 2 5 4 3 2 indexes elements 

array([4, 9, 7, 6])

In [68]:
ar1[-2:-6:-2] # begin to end+1 which means from -2 to -5 and in it select every second element

array([6, 2])

In [70]:
ar1[-2:-6:-1] 

array([ 6,  5,  2, 22])

1. In forward direction, of end value is 0, then result is always empty.
2. In backward direction, if end value is -1, then result  is always empty.

In [71]:
ar1[5:0]

array([], dtype=int32)

In [73]:
ar1[-2:-1:-1]

array([], dtype=int32)

In [75]:
ar1[::-1] # reverse of the array.

array([ 7,  6,  5,  2, 22,  3,  4,  9,  7,  6,  5,  4])

In [76]:
ar2=np.arange(1,17).reshape(4,4)
print(ar2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [77]:
# select 6 7
    #   10 11
    
ar2[1:3,1:3]

array([[ 6,  7],
       [10, 11]])

In [78]:
# select 5 8
 #       9 12 

In [80]:
ar2[1:3,0::3] # step size for column should be 3

array([[ 5,  8],
       [ 9, 12]])

In [81]:
ar2[::3,::3]

array([[ 1,  4],
       [13, 16]])

In [82]:
l2=np.arange(1,25).reshape(2,3,4)
print(l2)
print(l2.ndim)
print(l2.shape)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
3
(2, 3, 4)


In [83]:
l2[:,:,:1]

array([[[ 1],
        [ 5],
        [ 9]],

       [[13],
        [17],
        [21]]])

In [85]:
l2[:,2:,:]

array([[[ 9, 10, 11, 12]],

       [[21, 22, 23, 24]]])

In [87]:
l2[:,2:,1:3]

array([[[10, 11]],

       [[22, 23]]])

In [88]:
l2[:1,:1,:]

array([[[1, 2, 3, 4]]])

In [92]:
# # if we use 1 index directly,then we won't get 3d array and we will get 2D array here 
l2[1]

array([[13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [90]:
l2[1,0] # if we use two indexes directly,then we won't get 3d array and we will get 1D array here 

array([13, 14, 15, 16])

# lec 5
##  Numpy Advanced Indexing

1. By using slice operator,we can access multiple elements but should be in order.
2. for 1D slicing: array[begin:end:step]
2. for 2D slicing: array[begin:end:step,begin:end:step]
3. for 3D slicing: array[begin:end:step,begin:end:step,begin:end:step]

In [2]:
import numpy as np
a=np.array([1,2,3,4,5,7,8,8,4,5,63,2,2])
indexes=np.array([0,2,7])
print(a[indexes])

[1 3 8]


In [7]:
a[[0,2,7]] # this process only applicable for the arrays not lists.
# my assumption  of understanding here.
# here we given two squarebrackets which means go into the first array and give the corresponding index elements. 

array([1, 3, 8])

In [8]:
# here we can access same element multiple times.
a[[1,2,4,5,6,3,1,2]]

array([2, 3, 5, 7, 8, 4, 2, 3])

# Accessing elements of 2D array

In [10]:
l1=np.arange(1,17).reshape(4,4)
print(l1)
print(l1.ndim)
print(l1.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
2
(4, 4)


In [17]:
l1[[0,1,2,3],[0,1,2,3]]

array([ 1,  6, 11, 16])

In [18]:
# print 1,7,12,14
l1[[0,1,2,3],[0,2,3,1]]
# see here we are not using any slicing since , these are arbitrary elements.

array([ 1,  7, 12, 14])

In [20]:
# the elements present at (1,0),(3,2) will be selected.
l1[[1,3],[0,2]]

array([ 5, 15])

# Accessing elements of 3D array

In [ ]:
Syntax:
    array[[indexes of 2d array] ,[row indexes],[column indexes]]

In [24]:
l2[[0,1,0],[1,2,1],[3,2,0]]

# selects(0,1,3),(1,2,2) and (0,1,0)

array([ 8, 23,  5])

In [27]:
l2=np.arange(1,25).reshape(2,3,4)
print(l2)
print(l2.ndim)
print(l2.shape)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
3
(2, 3, 4)


In [28]:
l2[[0,1,0],[1,2,1],[3,2,0]]

array([ 8, 23,  5])

In [32]:
l2[[0,0,0,0],[0,1,2,1],[0,1,2,2]]

array([ 1,  6, 11,  7])

### how to select the elements based on some condition

In [34]:
a

array([ 1,  2,  3,  4,  5,  7,  8,  8,  4,  5, 63,  2,  2])

In [38]:
a>6

array([False, False, False, False, False,  True,  True,  True, False,
       False,  True, False, False])

In [39]:
a[a>6]

array([ 7,  8,  8, 63])

## slicing vs Advanced indexing

In [44]:
l1= [10,20,30,40]
l2=l1[::] # to create a new copy ,we can use slicing this way also. # deep copy
print(id(l1))
print(id(l2))

2101472202304
2101450250816


In [45]:
l3=l1 # without slicing we done here. so both have same reference. # shallow copy
print(id(l1))
print(id(l3))

2101472202304
2101472202304


In [52]:
a1=np.array([1,2,3,4,5,6,7,4,3,3])
a2=a1[0:4] # like view() works here.
print(a1)
print(a2)

[1 2 3 4 5 6 7 4 3 3]
[1 2 3 4]


In [53]:
a1[0]=88888
print(a1)
print(a2) # see the change is reflecting in the a2 also.

[88888     2     3     4     5     6     7     4     3     3]
[88888     2     3     4]


 ### But in the case of the advanced indexing, a new copy will be created.

In [57]:
import numpy as np
a1=np.array([1,2,3,4,5,7,8,8,4,5,63,2,2])
a2=a1[[0,2,6,8]]


In [58]:
print(a1)
print(a2)

[ 1  2  3  4  5  7  8  8  4  5 63  2  2]
[1 3 8 4]


In [59]:
a1[0]=900

In [60]:
print(a1)
print(a2)

[900   2   3   4   5   7   8   8   4   5  63   2   2]
[1 3 8 4]


In [ ]:
# lec 6
## go through the notes once.