In [1]:
import numpy as np
a=np.array([10,20,30,40])
print(a)

[10 20 30 40]


In [2]:
a[2]=100

In [3]:
a

array([ 10,  20, 100,  40])

In [4]:
b=np.array([[1,2,3],
             [4,5,6],
           [7,"hello",9]])


In [5]:
b

array([['1', '2', '3'],
       ['4', '5', '6'],
       ['7', 'hello', '9']], dtype='<U11')

In [6]:
type(b)

numpy.ndarray

In [7]:
type(b[0,2])

numpy.str_

In [8]:
print(b[2,2].dtype) # a unicode string with 1 byte

<U1


In [9]:
# if any element in the array is string datatype, then all the elements will also be considered as strings only.

In [14]:
c=np.array([['1', '2', '3'],
       ['4', '5', '6'],
       ['7', '5', '9']], dtype=np.int32) # here we are conveting it to the datatype to int.

In [13]:
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 5, 9]])

In [23]:
# we can also define the datatype we need.
d=np.array([['1', '2', '3'],
       ['4', '5', '6'],
       ['7', 'hello', '9']], dtype=np.int32)  # this is not possible since hello is present

ValueError: invalid literal for int() with base 10: 'hello'

In [24]:
c=np.array([['1', '2', '3'],
       ['4', '5', '6'],
       ['7', '5', '9']]) 

In [25]:
c

array([['1', '2', '3'],
       ['4', '5', '6'],
       ['7', '5', '9']], dtype='<U1')

In [26]:
print(c.astype(int)) # type casting to the integers datatype

[[1 2 3]
 [4 5 6]
 [7 5 9]]


In [29]:
d=np.array([['1', '2', '3'],
       ['4', '5', '6'],
       ['7', '5', '9']], dtype='<U2') # here we are mentioning the datatype as U2 

In [30]:
d.dtype

dtype('<U2')

# full():
 1. we need to give shape of the array and the value we want to fill it with .

In [31]:
np.full((2,3,4),7)

array([[[7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7]],

       [[7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7]]])

In [32]:
np.full((2,4),7)

array([[7, 7, 7, 7],
       [7, 7, 7, 7]])

In [40]:
# empty will reserves the space without initialaizing any values here and provides some  default values present in the memory.

a=np.empty((3,4))

In [41]:
a

array([[1.01855798e-312, 1.08221785e-312, 1.01855798e-312,
        9.54898106e-313],
       [1.14587773e-312, 1.03977794e-312, 1.23075756e-312,
        1.18831764e-312],
       [1.01855798e-312, 9.76118064e-313, 1.16709769e-312,
        1.90979621e-312]])

In [46]:
x=np.arange(0,1005,5)

In [47]:
print(x)

[   0    5   10   15   20   25   30   35   40   45   50   55   60   65
   70   75   80   85   90   95  100  105  110  115  120  125  130  135
  140  145  150  155  160  165  170  175  180  185  190  195  200  205
  210  215  220  225  230  235  240  245  250  255  260  265  270  275
  280  285  290  295  300  305  310  315  320  325  330  335  340  345
  350  355  360  365  370  375  380  385  390  395  400  405  410  415
  420  425  430  435  440  445  450  455  460  465  470  475  480  485
  490  495  500  505  510  515  520  525  530  535  540  545  550  555
  560  565  570  575  580  585  590  595  600  605  610  615  620  625
  630  635  640  645  650  655  660  665  670  675  680  685  690  695
  700  705  710  715  720  725  730  735  740  745  750  755  760  765
  770  775  780  785  790  795  800  805  810  815  820  825  830  835
  840  845  850  855  860  865  870  875  880  885  890  895  900  905
  910  915  920  925  930  935  940  945  950  955  960  965  970  975
  980 

1. If any particular data is missing in the dataset, then we can use nan (not a number) in those fields.

In [49]:
print(np.nan)

nan


In [50]:
print(np.inf)

inf


In [54]:
print(np.isnan(100)) # helps to check whether it is a nan or not.
# returns False if it is a number.

False


In [55]:
print(np.isnan(np.nan))

True


In [56]:
print(np.isinf(np.inf))

True


In [58]:
print(np.isinf(1))

False


In [63]:
print(np.sqrt(-1))
print(np.isnan(np.sqrt(-1))) # since it is a complex number , it will returns True with a warning.

nan
True


C:\Users\Phanindra Reddy\AppData\Local\Temp\ipykernel_12720\1917894831.py:1: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-1))
C:\Users\Phanindra Reddy\AppData\Local\Temp\ipykernel_12720\1917894831.py:2: RuntimeWarning: invalid value encountered in sqrt
  print(np.isnan(np.sqrt(-1))) # since it is a complex number , it will returns True with a warning.


In [64]:
print(np.array([10])/0)
print(np.isinf(np.array([10])/0)) # returns True since it is inf and also a warning will comes here.

[inf]
[ True]


C:\Users\Phanindra Reddy\AppData\Local\Temp\ipykernel_12720\1911952967.py:1: RuntimeWarning: divide by zero encountered in true_divide
  print(np.array([10])/0)
C:\Users\Phanindra Reddy\AppData\Local\Temp\ipykernel_12720\1911952967.py:2: RuntimeWarning: divide by zero encountered in true_divide
  print(np.isinf(np.array([10])/0)) # returns True since it is inf and also a warning will comes here.


# insertion and deletion of elements in the array

# append()

In [65]:
a=np.array([1,2,3,45,34])

In [66]:
a

array([ 1,  2,  3, 45, 34])

In [67]:
print(a)

[ 1  2  3 45 34]


In [73]:
# append will add the elements in the last .
print(np.append(a,[10,20,30])) # it won't append to the original array here. we need to assign it to the variable.

[ 1  2  3 45 34 10 20 30]


In [75]:
a=np.append(a,[10,20,30])

In [76]:
a

array([ 1,  2,  3, 45, 34, 10, 20, 30])

# insert()
 1. to insert the element at particular index,we need to use insert()

In [80]:
np.insert(a,3,[33,44]) # at index 3 position ,we inserted 2 elements here.

array([ 1,  2,  3, 33, 44, 45, 34, 10, 20, 30])

In [3]:
a

array([10, 20, 30, 40])

# delete():
1. In the case of delete (), we will treat axis=0 means row wise and axis=1 means along column wise.

In [6]:
np.delete(a,1) # deletes the element at 1st index. but not the original array element.
# we need to assign it to a varibale and store it.

array([10, 30, 40])

In [7]:
a

array([10, 20, 30, 40])

In [25]:
a1=np.array([[1,2,3],[4,5,6]])

In [9]:
a1

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
np.delete(a1,2)
# 3 will be deleted. this function will treats as single 1D array and deletes element at that index position

array([1, 2, 4, 5, 6])

In [16]:
np.delete(a1,3)

array([1, 2, 3, 5, 6])

In [17]:
np.delete(a1,5)

array([1, 2, 3, 4, 5])

In [20]:
a1 # but the original array doesn't change. to change it assign a1 to that command.

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
a1=np.delete(a1,5) # 6 is deleted here.

In [27]:
a1

array([1, 2, 3, 4, 5])

In [36]:
# we can pass the second parameter also here.
a2=np.array([[1,2,3],[4,5,6]])
np.delete(a2,1,0) # this will delete the second row here
# it means delete the row with index 1 here.
# second parameter 0 means row wise

array([[1, 2, 3]])

In [35]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
np.delete(a2,1,1)  # column with 1st index will be deleted here.
# last parameter 1 means along column wise 

array([[1, 3],
       [4, 6]])

In [40]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [41]:
a2.size

6

In [42]:
a2.shape

(2, 3)

In [43]:
a2.resize(3,2)

In [44]:
a2

array([[1, 2],
       [3, 4],
       [5, 6]])

#flatten():
 1. this works as like copy() which returns the copy of the array .

In [48]:
print(a2.flatten()) 
# this will convert to 1D aray here. which means flatten to a single dimensional array.

[1 2 3 4 5 6]


In [46]:
a2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [50]:
print(a2.ravel())

[1 2 3 4 5 6]


In [54]:
var1=a2.flatten()
var1[2]=100 # here we try to change to any element value and it doesn't affect the original array

In [55]:
var1

array([  1,   2, 100,   4,   5,   6])

In [56]:
a2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [57]:
var2=a2.ravel() # ravel acts like view() .
var2[4]=900

In [58]:
var2

array([  1,   2,   3,   4, 900,   6])

In [59]:
a2

array([[  1,   2],
       [  3,   4],
       [900,   6]])

In [61]:
a2.T # capiatal T means transpose. Instead of np.transpose(), we can give as T

array([[  1,   3, 900],
       [  2,   4,   6]])

 # Swapaxes():
    1. This will acts as like transpose().

In [63]:
a2.swapaxes(0,1)

array([[  1,   3, 900],
       [  2,   4,   6]])

In [64]:
a2

array([[  1,   2],
       [  3,   4],
       [900,   6]])

# concatenate():

In [66]:
a1=np.arange(1,11).reshape(2,5)
a2=np.arange(3,13).reshape(2,5)
print(a1)
print(a2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 3  4  5  6  7]
 [ 8  9 10 11 12]]


In [70]:
np.concatenate((a1,a2),axis=0) # along row wise here

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [ 3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12]])

In [72]:
np.concatenate((a1,a2),axis=1) # along column wise concatenated here.

array([[ 1,  2,  3,  4,  5,  3,  4,  5,  6,  7],
       [ 6,  7,  8,  9, 10,  8,  9, 10, 11, 12]])

In [74]:
np.stack((a1,a2)) # but stack will gives in  a new dimension only ,not in a single 2D

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[ 3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12]]])

In [75]:
np.stack((a1,a2),axis=0)

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[ 3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12]]])

In [76]:
np.stack((a1,a2),axis=1)

array([[[ 1,  2,  3,  4,  5],
        [ 3,  4,  5,  6,  7]],

       [[ 6,  7,  8,  9, 10],
        [ 8,  9, 10, 11, 12]]])

In [78]:
np.hstack((a1,a2))

array([[ 1,  2,  3,  4,  5,  3,  4,  5,  6,  7],
       [ 6,  7,  8,  9, 10,  8,  9, 10, 11, 12]])

In [79]:
np.vstack((a1,a2))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [ 3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12]])

In [80]:
c=np.array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [ 3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12]])

In [81]:
c

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [ 3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12]])

In [83]:
print(np.split(c,2,axis=0))

[array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]]), array([[ 3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12]])]


In [87]:
print(np.split(c,4,axis=0))

[array([[1, 2, 3, 4, 5]]), array([[ 6,  7,  8,  9, 10]]), array([[3, 4, 5, 6, 7]]), array([[ 8,  9, 10, 11, 12]])]


In [88]:
d=np.array([[ 1,  2,  3,  4,  5,6],
       [ 6,  7,  8,  9, 10,11],
       [ 3,  4,  5,  6,  7,12],
       [ 8,  9, 10, 11, 12,13]])

In [90]:
np.split(d,2,axis=1) # first three columns separately and then next 3 columns separately

[array([[ 1,  2,  3],
        [ 6,  7,  8],
        [ 3,  4,  5],
        [ 8,  9, 10]]),
 array([[ 4,  5,  6],
        [ 9, 10, 11],
        [ 6,  7, 12],
        [11, 12, 13]])]

In [92]:
np.random.randint(10,100,size=(2,3,4))

array([[[29, 67, 63, 85],
        [77, 91, 23, 68],
        [20, 53, 45, 24]],

       [[95, 64, 72, 12],
        [23, 64, 80, 33],
        [56, 89, 88, 12]]])

In [94]:
np.random.binomial(10,p=0.5,size=(5,5))

array([[8, 2, 6, 5, 5],
       [3, 5, 4, 6, 6],
       [6, 4, 3, 5, 5],
       [3, 3, 3, 6, 6],
       [7, 8, 4, 7, 4]])

In [96]:
np.random.normal(loc=170,scale=15,size=(5,7))

array([[163.68800635, 185.81645895, 155.85409701, 186.16851624,
        170.84693802, 175.86366219, 201.86298318],
       [159.40472588, 167.48357063, 162.86116199, 145.28730044,
        153.12163222, 173.20792761, 173.56725815],
       [178.46651444, 194.22318793, 193.0610491 , 179.75549762,
        179.09381658, 153.67341944, 163.65505431],
       [167.00303124, 159.45272305, 174.83214423, 151.64438266,
        175.89483747, 162.32726623, 184.28478455],
       [172.61648469, 169.32045426, 184.5533725 , 170.86830411,
        157.89732981, 180.0539144 , 165.65531394]])

In [100]:
print(np.random.choice([1,2,4,5,6,7],size=(3,4)))

[[1 4 4 6]
 [5 2 7 6]
 [7 6 2 5]]


# save():

In [103]:
# exporting and importing numpy arrays
np.save("myarray.npy",a)

In [104]:
b=np.load("myarray.npy")

In [105]:
print(b)

[10 20 30 40]


# saving in csv format

In [108]:
np.savetxt("myarray.csv",a2,delimiter=",")

In [111]:
a=np.loadtxt("myarray.csv",delimiter=",")

In [112]:
a

array([[ 3.,  4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11., 12.]])