# Python Numpy INtroduction
## Lec 1

In [1]:
# array is a collection of similar type of elements 

# 1D--> Vector
# 2D--> Matrix
# 3D--> Tensor

1. Numpy is used with packages like SciPy (Scientific Python) and Mat-plotlib (plotting library) and this makes it capable to replace MATLAB
2. Numpy is often called as an alternate for MATLAB (a programming platform designed specifically for enginners and scientists for Data Analysis,Developing Algorithms ,create models and applications etc.

# lec 2
## How to install Numpy (Anaconda)

# lec 3
## Writing compiling Executing programs in Numpy 

# work with jupyter notebook
1. To run program press ctrl+enter
2. to run the command as well as insert a cell below- shift+enter
3. to insert a cell below just press-"b" ( in command mode only works)
4. to delete a cell - press esc button (to go to command mode as in Edit mode you can't delete the cell ) and then "d" two times.
5. In command mode if you press "a" then a new cell will be inserted above.

In [2]:
# in help section,we can find out all the keyboard shortcuts

In [3]:
# to mark something as comment we press escape and then 1 and shift+enter to execute

# 2+5

# comment section

## lec 4
## creating one dimensional array using numpy

In [4]:
import numpy as np
a=[1,2,3,4,5,6]
b=(6,7,7,897,5,3,2,4,6,787,87)
arr1=np.array(a)
arr2=np.array(b) # we can pass argument as list or tuple to the array function.

In [5]:
arr1 # directly gives the array with commas 

array([1, 2, 3, 4, 5, 6])

In [6]:
print(arr1)

[1 2 3 4 5 6]


In [7]:
print(arr2)

[  6   7   7 897   5   3   2   4   6 787  87]


In [8]:
ls=[]
n=int(input("Enter the range of numbers:"))
for i in range(n):
    a=int(input("Enter number:"))
    ls.append(a)
arr1=np.array(ls)
print(arr1)

Enter the range of numbers:6
Enter number:54
Enter number:90
Enter number:43
Enter number:32
Enter number:12
Enter number:90
[54 90 43 32 12 90]


# write a program which takes a range of numbers and convert it to array

In [9]:
ls=[]
n=int(input("Enter the range of numbers:"))
for i in range(n):
    a=int(input("Enter number:"))
    ls.append(a)
arr1=np.array(ls)
print(arr1)

Enter the range of numbers:3
Enter number:21
Enter number:3
Enter number:9
[21  3  9]


# lec 5
## creating two dimensional array using numpy

In [12]:
a1=[[1,2,3],[4,5,6]]
arr1=np.array(a1)

In [13]:
print(arr1)

[[1 2 3]
 [4 5 6]]


In [16]:
a2=[[1,2,3],[4,5,6],[7,8,9]]
arr2=np.array(a2)
print(arr2)
print("Dimension of array is:",arr2.ndim)
print("shape of array is :",arr2.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Dimension of array is: 2
shape of array is : (3, 3)


# lec 6
## Numpy functions in Python

In [18]:
arr=np.zeros(6)

In [19]:
print(arr)

[0. 0. 0. 0. 0. 0.]


In [20]:
arr1=np.zeros((4,5))

In [21]:
print(arr1)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [24]:
arr1=np.zeros(((4,5,6)))

In [25]:
print(arr1)

[[[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]]


In [26]:
arr1

array([[[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]]])

In [32]:
arr=np.ones(11)

In [33]:
arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [34]:
arr1=np.ones((3,4))

In [35]:
arr1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [36]:
arr2=np.ones(((3,4,5)))

In [37]:
arr2

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [46]:
arr=np.eye(3)

In [47]:
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [48]:
arr1=np.eye(5,8) # here no need to give twice braces

In [49]:
arr1

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.]])

In [50]:
a=np.diag([1,2,3,4,5,3,5])

In [51]:
a

array([[1, 0, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0, 0],
       [0, 0, 0, 4, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0],
       [0, 0, 0, 0, 0, 3, 0],
       [0, 0, 0, 0, 0, 0, 5]])

In [52]:
print(a)

[[1 0 0 0 0 0 0]
 [0 2 0 0 0 0 0]
 [0 0 3 0 0 0 0]
 [0 0 0 4 0 0 0]
 [0 0 0 0 5 0 0]
 [0 0 0 0 0 3 0]
 [0 0 0 0 0 0 5]]


In [53]:
# to get the diagonal elements then we can give as 
np.diag(a) # simply gives all the diagonal elements

array([1, 2, 3, 4, 5, 3, 5])

In [59]:
a1=np.random.randint(3,12,6)

In [60]:
a1

array([ 3,  9, 11,  7,  8,  3])

In [61]:
arr=np.random.rand(5)

In [63]:
arr

array([0.45151159, 0.22993048, 0.12147821, 0.88078031, 0.83524205])

In [3]:
arr1=np.random.rand(2,5)

In [4]:
arr1

array([[0.95092305, 0.97354804, 0.77780306, 0.82460722, 0.88197839],
       [0.17897834, 0.6611957 , 0.83911996, 0.06213826, 0.69741782]])

In [5]:
arr1.size # size gives the no of elements present in the matrix

10

In [68]:
a1=np.random.randn(8)

In [69]:
a1

array([ 0.44082114,  0.37988321,  0.30977582, -0.94052155, -1.18554831,
        0.02568624,  0.62763763,  1.46065879])

In [70]:
a1=np.random.randn(4,8)

In [71]:
a1

array([[ 1.65149739, -0.17326832,  0.15371403, -0.2113012 , -1.18647957,
         0.5650255 , -0.54491269, -1.19369142],
       [ 1.0366623 , -0.24635215, -0.11141378,  0.7055328 , -1.71230285,
        -0.6827302 ,  1.37268989,  0.23337741],
       [-0.48835236,  0.53934267, -1.05204752, -0.97435552, -2.21767338,
        -0.22739695, -0.61079317, -0.29382429],
       [ 0.88710962,  0.37335999,  1.04822676,  1.6195504 ,  0.3123784 ,
        -0.42248799, -0.98860686,  1.29038235]])

# lec 7
## Indexing and slicing of Numpy array

In [1]:
import numpy as np
a=[]
n=int(input("enter the no of values:"))
for i in range(n):
    val=int(input("enter the numbers:"))
    a.append(val)
arr=np.array(a)
for i in range(arr.size):
    print(arr[i]) # indexing starts from 0

enter the no of values:5
enter the numbers:2
enter the numbers:3
enter the numbers:4
enter the numbers:5
enter the numbers:1
2
3
4
5
1


1. Array supports indexing from left to right as well as from right to left.
2. When indexing from left to right,it starts with 0
3. When indexing from right to left,it starts with -1
4. Indexing technique of array is much similar to the list.

syntax: arr_name[start:end:step]    # by default the step will be +1 here

In [7]:
# Array slicing
arr[1:] # starts from 1 and ends to last element

array([3, 4, 5, 1])

In [9]:
arr[:] # gives entire array since first and last are both considered as default values here.

array([2, 3, 4, 5, 1])

In [10]:
arr[-4:-1]

array([3, 4, 5])

In [11]:
arr[:5]

array([2, 3, 4, 5, 1])

In [12]:
arr[:89] #  start from 0 index and here it won't give error but gives the maxium range elements present in it

array([2, 3, 4, 5, 1])

In [13]:
arr[1:4]

array([3, 4, 5])

In [14]:
# sum of array elements
sum=0
for i in range(arr.size):
    sum=sum+arr[i]
    
print(sum)

15


# lec 8
## Reshaping of array in Numpy

In [15]:
a1=np.random.randint(1,15,12) # gives 1D array with 12 elements

In [16]:
a1

array([ 4,  4, 14, 10,  5, 14,  6,  5,  9,  8,  3,  1])

In [19]:
print(a1.shape)

(12,)


In [21]:
# for reshaping ,we must reshape in a way such that the product combination should be the original shape value
 # like 12 can be written as 12*1, 3*4,6*2 etc .
    # for other combinations it will give error

In [22]:
# converting to 2D array
a1=a1.reshape(3,4)

In [23]:
a1

array([[ 4,  4, 14, 10],
       [ 5, 14,  6,  5],
       [ 9,  8,  3,  1]])

In [24]:
a1=a1.reshape(5,3)

ValueError: cannot reshape array of size 12 into shape (5,3)

In [26]:
a1=a1.reshape(2,6)

In [27]:
a1

array([[ 4,  4, 14, 10,  5, 14],
       [ 6,  5,  9,  8,  3,  1]])

In [28]:
print("After Reshaping:",a1.ndim)

After Reshaping: 2


In [29]:
# Now we will convert this back to the 1D array
# To convert back to 1D array from any Multi dimensional array,just give the size for it.
a1=a1.reshape(12)

In [30]:
a1

array([ 4,  4, 14, 10,  5, 14,  6,  5,  9,  8,  3,  1])

In [31]:
# converting to 3D array
a1=a1.reshape(2,2,3)

In [32]:
a1

array([[[ 4,  4, 14],
        [10,  5, 14]],

       [[ 6,  5,  9],
        [ 8,  3,  1]]])

In [33]:
a1.ndim

3

In [34]:
# converting from 3D array to again 1D array
a1=a1.reshape(12)

In [35]:
a1

array([ 4,  4, 14, 10,  5, 14,  6,  5,  9,  8,  3,  1])

In [36]:
a1.ndim

1

In [37]:
# suppose now we have the no of rows or no of columns with us .
# in this case we want python to calculate exact value required and give us the reshape array
# so, we can use -1 in the place where u don't know the value just as shown below

In [38]:
a1=a1.reshape(3,-1) # here we know only 3 rows ,it have.. so python will calculate other value required in place of -1.

In [39]:
a1

array([[ 4,  4, 14, 10],
       [ 5, 14,  6,  5],
       [ 9,  8,  3,  1]])

In [40]:
a1.ndim

2

In [43]:
a1=a1.reshape(-1,6) # here we know that it should have 6 columns but we don't know the no of rows
# python itself calculates this and gives us the result.
# in place of -1, it will take 2 and gives the reshaped array

In [44]:
a1

array([[ 4,  4, 14, 10,  5, 14],
       [ 6,  5,  9,  8,  3,  1]])

In [48]:
a1=a1.reshape(3,2,-1) # the -1 entry will be calculated by the system.

In [49]:
a1

array([[[ 4,  4],
        [14, 10]],

       [[ 5, 14],
        [ 6,  5]],

       [[ 9,  8],
        [ 3,  1]]])

# lec 9
## seed function in Python

In [101]:
np.random.seed(4)
a=np.random.randint(1,7,4)

In [102]:
a

array([3, 6, 2, 1])

In [103]:
a 

array([3, 6, 2, 1])

In [104]:
a

array([3, 6, 2, 1])

In [105]:
a

array([3, 6, 2, 1])

In [106]:
a # since seed is given , everytime we try to print we are geeting same random set here

array([3, 6, 2, 1])

In [77]:
np.random.seed(10) # we can insert any value here. it doesn't affect anything .

In [107]:
b=np.random.randint(1,15,15)

In [108]:
b # it will return the same random numbers till we change the integer as paased to set.

array([ 8,  9,  3, 10, 11, 13,  8, 14,  8,  8, 10,  9,  5,  3, 13])

In [109]:
b

array([ 8,  9,  3, 10, 11, 13,  8, 14,  8,  8, 10,  9,  5,  3, 13])

In [110]:
b

array([ 8,  9,  3, 10, 11, 13,  8, 14,  8,  8, 10,  9,  5,  3, 13])

In [112]:
 # inside the seed value,it doesn't matter here. 
c=np.random.randint(5,10,7)

In [113]:
c

array([8, 9, 5, 6, 8, 5, 5])

In [115]:
np.random.seed(1)
c

array([8, 9, 5, 6, 8, 5, 5])

In [116]:
 # to change the fixed set values,just to get a new set ,we need to just change the seed value above there.

In [117]:
np.random.seed(5)

In [118]:
d=np.random.randint(6,12,4)

In [119]:
d

array([ 9, 11,  6,  7])

# lec 10
## creating Two dimensional array user input


In [ ]:
Indexing /Slicing using Single bracket notation
     0      1      2
0  [0,0]  [0,1]  [0,2]
1  [1,0]  [1,1]  [1,2]
2  [2,0]  [2,1]  [2,2]

In [121]:
import numpy as np
mat=[]
row=int(input("enter the no of rows:"))
col=int(input("enter the no of columns:"))
for i in range(row):
    a=[]
    for j in range(col):
        val=int(input("enter the number:"))
        a.append(val)
    mat.append(a)
arr=np.array(mat)
for i in range(row):
    for j in range(col):
        print(arr[i][j],end=" ")
    print()
print(type(arr))

enter the no of rows:4
enter the no of columns:2
enter the number:2
enter the number:3
enter the number:4
enter the number:3
enter the number:21
enter the number:56
enter the number:43
enter the number:56
2 3 
4 3 
21 56 
43 56 
<class 'numpy.ndarray'>


# lec 11
## slicing 2D array in Numpy

In [122]:
arr

array([[ 2,  3],
       [ 4,  3],
       [21, 56],
       [43, 56]])

In [123]:
arr[:2] # see here 0 and 1 rows with all column values are taken.

array([[2, 3],
       [4, 3]])

In [124]:
a=np.array([[1,2,3,4],[23,4,5,6],[3,7,56,32]]) # neatly understand.it is so much easy concept here.

In [125]:
a

array([[ 1,  2,  3,  4],
       [23,  4,  5,  6],
       [ 3,  7, 56, 32]])

In [127]:
a[1:] #rows 1 and 2 will present

array([[23,  4,  5,  6],
       [ 3,  7, 56, 32]])

In [129]:
a[:,2:3] # if all rows u want then u need to give a colon here which indicate all values from start to end.

array([[ 3],
       [ 5],
       [56]])

In [130]:
a[:,1:4]

array([[ 2,  3,  4],
       [ 4,  5,  6],
       [ 7, 56, 32]])

In [131]:
a[1:2,1:4]

array([[4, 5, 6]])

In [137]:
import numpy as np
np.random.seed(1)
b=np.random.randint(1,100,20).reshape(4,5)

In [138]:
b

array([[38, 13, 73, 10, 76],
       [ 6, 80, 65, 17,  2],
       [77, 72,  7, 26, 51],
       [21, 19, 85, 12, 29]])

In [139]:
b[2:]

array([[77, 72,  7, 26, 51],
       [21, 19, 85, 12, 29]])

In [140]:
b[2:,2:]

array([[ 7, 26, 51],
       [85, 12, 29]])

In [141]:
# extract 7,26,51
b[2:3,2:]

array([[ 7, 26, 51]])

# lec 12
## view vs copy Python Numpy

In [6]:
import numpy as np
a=np.array([10,20,30,405,506,89,96,100])
slicing=a[3:6] # view -->shallow copy
slicing[:]=0 # updating all elements to zero here
a

array([ 10,  20,  30,   0,   0,   0,  96, 100])

In [7]:
# see above that all elements are updated to zero since we used view here

In [8]:
a=np.array([10,20,30,405,506,89,96,100])
slicing=a[3:6].copy() # copy-->deep copy
slicing[:]=0 # updating all elements to zero here
a

array([ 10,  20,  30, 405, 506,  89,  96, 100])

In [9]:
a # no changes have done here .

array([ 10,  20,  30, 405, 506,  89,  96, 100])

# lec 13
## Conditional Selection in Python Numpy

In [10]:
arr=np.arange(1,16)

In [11]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [12]:
# condition based statements
arr>10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True])

In [16]:
b=arr>10 # this contains a array with true or false based on the given condition.

In [17]:
b

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True])

In [19]:
arr[b] # wherever true is present all those elements will present in the output.

array([11, 12, 13, 14, 15])

In [21]:
arr[arr>5] # returns an array where arr elements are greater than 5

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [22]:
arr[arr<5]

array([1, 2, 3, 4])

In [25]:
arr[arr==100] # 100 is not present .so empty array

array([], dtype=int32)

In [26]:
arr[arr==7]

array([7])

In [27]:
# print all the even elements present in the array
arr[arr%2==0]

array([ 2,  4,  6,  8, 10, 12, 14])

In [28]:
arr[arr%2!=0] # selection only: gives all the old elements present in array

array([ 1,  3,  5,  7,  9, 11, 13, 15])

In [29]:
arr[arr%2==0]=1 # selecting and updating all the even  elements to 1 here.

In [30]:
arr

array([ 1,  1,  3,  1,  5,  1,  7,  1,  9,  1, 11,  1, 13,  1, 15])

# lec 14
## Various operations in Numpy

In [31]:
a=np.arange(1,12)

In [32]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [34]:
a*2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

In [35]:
a+2

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [36]:
a-2

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [37]:
a/2

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5])

In [39]:
a/0

C:\Users\Phanindra Reddy\AppData\Local\Temp\ipykernel_17492\4102073204.py:1: RuntimeWarning: divide by zero encountered in true_divide
  a/0


array([inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf])

In [40]:
a**2

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121], dtype=int32)

In [41]:
b=np.arange(2,13)

In [42]:
b

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [43]:
a+b

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [44]:
a-b

array([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1])

In [45]:
a*b

array([  2,   6,  12,  20,  30,  42,  56,  72,  90, 110, 132])

In [46]:
a/b

array([0.5       , 0.66666667, 0.75      , 0.8       , 0.83333333,
       0.85714286, 0.875     , 0.88888889, 0.9       , 0.90909091,
       0.91666667])

In [47]:
a=np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)

In [48]:
b=np.array([11,22,13,43,653,26,17,58,19]).reshape(3,3)

In [49]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [50]:
b

array([[ 11,  22,  13],
       [ 43, 653,  26],
       [ 17,  58,  19]])

In [51]:
a*b # index wise multiplication

array([[  11,   44,   39],
       [ 172, 3265,  156],
       [ 119,  464,  171]])

In [52]:
a.dot(b) # matrix multiplication here

array([[ 148, 1502,  122],
       [ 361, 3701,  296],
       [ 574, 5900,  470]])

In [53]:
a-b

array([[ -10,  -20,  -10],
       [ -39, -648,  -20],
       [ -10,  -50,  -10]])

# lec 15
## Numpy array functions part 1

In [54]:
arr

array([ 1,  1,  3,  1,  5,  1,  7,  1,  9,  1, 11,  1, 13,  1, 15])

In [55]:
np.min(arr)

1

In [56]:
np.max(arr)

15

In [57]:
np.sum(arr)

71

In [59]:
np.argmin(arr) # gives the index position where min element is present in the array.

0

In [61]:
np.argmax(arr) # at 14th index ,the max element is present

14

In [66]:
np.sqrt(arr) # square root of every element

array([1.        , 1.        , 1.73205081, 1.        , 2.23606798,
       1.        , 2.64575131, 1.        , 3.        , 1.        ,
       3.31662479, 1.        , 3.60555128, 1.        , 3.87298335])

In [64]:
np.sin(arr) # sin value of other number

array([ 0.84147098,  0.84147098,  0.14112001,  0.84147098, -0.95892427,
        0.84147098,  0.6569866 ,  0.84147098,  0.41211849,  0.84147098,
       -0.99999021,  0.84147098,  0.42016704,  0.84147098,  0.65028784])

In [65]:
np.cos(arr) # cos value of every number

array([ 0.54030231,  0.54030231, -0.9899925 ,  0.54030231,  0.28366219,
        0.54030231,  0.75390225,  0.54030231, -0.91113026,  0.54030231,
        0.0044257 ,  0.54030231,  0.90744678,  0.54030231, -0.75968791])

In [67]:
np.linspace(1,2,5) # between 1 and 2 print 5 values with same gap

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [68]:
print(np.linspace(1,10,5) )

[ 1.    3.25  5.5   7.75 10.  ]


# lec 16
## Numpy array functions part 2 

In [69]:
# create 2D array with fixed datatype

np.random.seed(1)
mat=np.random.randint(1,12,9).reshape(3,3)
mat

array([[ 6,  9, 10],
       [ 6,  1,  1],
       [ 2,  8,  7]])

In [70]:
mat

array([[ 6,  9, 10],
       [ 6,  1,  1],
       [ 2,  8,  7]])

In [72]:
np.sum(mat)

50

In [74]:
mat.sum() # both returns the same value.

50

In [75]:
np.min(mat)

1

In [76]:
np.max(mat)

10

In [77]:
np.min(mat,axis=0)

array([2, 1, 1])

In [78]:
np.min(mat,axis=1)

array([6, 1, 2])

In [79]:
np.cumsum(mat) # cummulative sum. # adding one element to every time . 
6,6+9,6+9+10,6+9+10+5, ........

array([ 6, 15, 25, 31, 32, 33, 35, 43, 50], dtype=int32)

In [81]:
np.sum(mat,axis=1) # row wise sum

array([25,  8, 17])

In [82]:
np.cumsum(mat,axis=1)

array([[ 6, 15, 25],
       [ 6,  7,  8],
       [ 2, 10, 17]], dtype=int32)

# lec 17
## Numpy array functions part3

# Shuffle 

In [83]:
# shuffles the array elements
np.random.seed(2)
a=np.random.randint(1,10,7)

In [84]:
a

array([9, 9, 7, 3, 9, 8, 3])

In [86]:
np.random.shuffle(a)

In [43]:
a

NameError: name 'a' is not defined

# unique

In [89]:
np.unique(a) # gives all the unique elements present in the array.

array([3, 7, 8, 9])

In [90]:
np.unique(a).size # counts the unique number of elements

4

In [92]:
np.unique(a,return_index=True,return_counts=True) 

(array([3, 7, 8, 9]),
 array([0, 4, 2, 1], dtype=int64),
 array([2, 1, 1, 3], dtype=int64))

# lec 18
## Python Numpy Stacking

In [4]:
import numpy as np
arr1=np.array([1,2,3,4])
arr2=np.array([5,6,7,8])

In [5]:
arr1

array([1, 2, 3, 4])

In [6]:
arr2

array([5, 6, 7, 8])

In [8]:
np.hstack((arr1,arr2))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [9]:
np.vstack((arr1,arr2))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [10]:
# stacking 2D array with fixed datatype
import numpy as np
np.random.seed(1)
arr1=np.random.randint(1,21,9).reshape(3,3)
arr2=np.random.randint(30,41,9).reshape(3,3)

In [11]:
arr1

array([[ 6, 12, 13],
       [ 9, 10, 12],
       [ 6, 16,  1]])

In [12]:
arr2

array([[30, 31, 37],
       [36, 39, 32],
       [34, 35, 32]])

In [14]:
np.hstack((arr1,arr2))

array([[ 6, 12, 13, 30, 31, 37],
       [ 9, 10, 12, 36, 39, 32],
       [ 6, 16,  1, 34, 35, 32]])

In [15]:
np.vstack((arr1,arr2))

array([[ 6, 12, 13],
       [ 9, 10, 12],
       [ 6, 16,  1],
       [30, 31, 37],
       [36, 39, 32],
       [34, 35, 32]])

# lec 19 & 20
## Numpy Practice Questions and Answers

1. create an array of 10 random integers

In [16]:
arr=np.random.randint(1,100,10)

In [17]:
arr

array([85, 12, 29, 30, 15, 51, 69, 88, 88, 95])

2. create an array from 10-20  elements

In [20]:
arr=np.arange(10,21)

In [21]:
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

3. create an array which contains value 5,10 times

In [23]:
# first we create an array with ones and then multiply it by 5
arr=np.ones(10)*5

In [24]:
arr

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

4. create a 1D array and convert it into 3*3 matrix

In [25]:
arr=np.arange(1,10).reshape(3,3)

In [26]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

5. create an array and then convert all the even numbers with 0.

In [27]:
arr=np.arange(1,10)

In [28]:
arr[arr%2==0]=0 # wherever even numbers are present, we are updating to the 0 value.

In [29]:
arr

array([1, 0, 3, 0, 5, 0, 7, 0, 9])

6. create a D array of size 3*3 but all the elements should be between 0 and 1.

In [30]:
arr=np.random.rand(9).reshape(3,3)

In [31]:
arr

array([[0.19810149, 0.80074457, 0.96826158],
       [0.31342418, 0.69232262, 0.87638915],
       [0.89460666, 0.08504421, 0.03905478]])

In [33]:
arr1=np.arange(1,17).reshape(4,4)

In [34]:
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [38]:
arr2=arr1[1:,1:3]

In [39]:
arr2

array([[ 6,  7],
       [10, 11],
       [14, 15]])

8. Concatenate 2D array horizontally and vertically.

In [40]:
arr1=np.arange(1,10).reshape(3,3)
arr2=np.arange(2,11).reshape(3,3)
np.hstack((arr1,arr2))

array([[ 1,  2,  3,  2,  3,  4],
       [ 4,  5,  6,  5,  6,  7],
       [ 7,  8,  9,  8,  9, 10]])

In [41]:
np.vstack((arr1,arr2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

# lec 21
## Numpy vs List

In [44]:
# proof to show arrays are faster than lists.

1. We can use timeit to find he running time(average/mean).
2. %timeit-> for getting the execution time of one statement.
3. %%timeit-> for multiline execution time.


In [46]:
%timeit 2+3 # for single statement

9.46 ns ± 0.174 ns per loop (mean ± std. dev. of 7 runs, 100000000 loops each)


In [48]:
%%timeit # for multiple statements
a=[]
for i in range(1,15):
    a.append(i*10)

1.5 µs ± 58.2 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [49]:
# list
%timeit [i**2 for i in range(1,11)]

3.09 µs ± 149 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [51]:
#array
%timeit np.arange(1,11)**2

1.4 µs ± 74 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [52]:
# here we can observe that time taken by array is very less compared to the list.

 # lec 22
   ## Searching an element in Numpy array

In [53]:
arr=np.array([10,20,340,34,40,50,40,56,40,23,40])

In [56]:
x=np.where(arr==40) # returns all the indices where 40 is present.

In [57]:
x

(array([ 4,  6,  8, 10], dtype=int64),)

1. we can also perform condition based searching using where() function.

In [60]:
res=np.where(arr%2==0)

In [61]:
res

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8, 10], dtype=int64),)

# search sorted
 This method performs a Binary search in the array and returns the index where the specified value would be inserted to maintain the search order.
    

In [62]:
x=np.searchsorted(arr,50)

In [63]:
x

2

In [65]:
# here we can perform searching from the right side also.
#The searching may also be performed from right side.

x=np.searchsorted(arr,100,side="right")

In [66]:
x

11